### ISSUE TITLE
Syncing services from many k8s clusters to single consul

### ISSUE THREAD

**Issue by mgrzybowski** [hashicorp/consul-k8s#101]
Hi
   I have consul servers outside k8s clusters and i'm traing to register services from many k8s cluster to this single central consul directory. It seems that the current sync service from k8s to consul is limited to single k8s cluster (in the same consul datacenter ) . 

From what i understand consul node name for sync is hardcoded:
https://github.com/hashicorp/consul-k8s/blob/aa7d80a934a1c2faf5ffe9b3bd0abba4e8754d14/catalog/from-k8s/resource.go#L258

What if node name for sync could be changed in config ( each k8s have its own unique node for service sync ) ? Will this allow to sync services from many k8s to single consul ( to the same consul datacenter )   ?

Kind Regards
    Marek Grzybowski

**Comment by lkysow** [comment]
Hi mgrzybowski, why does this cause you to not be able to sync from multiple k8s clusters?

**Comment by mgrzybowski** [comment]
Hi lkysow 
  The same consul node name  "k8s-sync" exists in each of  k8s cluster. You can not register the same consul node multiple times in the consul directory.

**Comment by lkysow** [comment]
Ahh I see, thanks for clarifying.

**Comment by praymann** [comment]
I'm not sure this is an issue.

I'm in the process of setting up this exact same situation:

> [...] consul servers outside k8s clusters and [...] register services from many k8s cluster to this single central consul directory

Given a unique tag via `consul-k8s-tag` as mentioned in https://github.com/hashicorp/consul-k8s/pull/103#issuecomment-505426930 the sync appears to "just work", no conflict of Nodes.

![image](https://user-images.githubusercontent.com/9577818/66351003-55411800-e922-11e9-8cc8-9f142abb13bf.png)

This issues calls out [L258](https://github.com/hashicorp/consul-k8s/blob/aa7d80a934a1c2faf5ffe9b3bd0abba4e8754d14/catalog/from-k8s/resource.go#L258) as the root of the issue, but I think [L257](https://github.com/hashicorp/consul-k8s/blob/aa7d80a934a1c2faf5ffe9b3bd0abba4e8754d14/catalog/from-k8s/resource.go#L257) makes this "just work". Document states:

> SkipNodeUpdate (bool: false) - Specifies whether to skip updating the node's information in the registration. This is useful in the case where only a health check or service entry on a node needs to be updated or when a register request is intended to update a service entry or health check. In both use cases, node information will not be overwritten, if the node is already registered. Note, if the paramater is enabled for a node that doesn't exist, it will still be created.

**Comment by lkysow** [comment]
Hi @praymann that looks like a good workaround! I think we'll still want to merge #103 simply because I understand why people might want to have the services registered to different nodes.

**Comment by david-yu** [comment]
Closing as the node name can now be set since #312 is merged.
