### ISSUE TITLE
Nodeport not updating consul on Node termination. 

### ISSUE THREAD

**Issue by himadrisingh** [hashicorp/consul-k8s#102]
1. We have pods running on k8s Node A/B, with replication 2. 
1. Nodeport service gets registered to Consul as expected.
1. Add a new k8s Node C to the cluster. 
1. Pod recreated on Node C. Node B has no pod now. 
1. Node C also get registered to Consul, but Node B still shows up on the consul catalog. 
1. Terminate Node B, things start failing. 

The service name remains same, just the underlying pods keep on moving.

**Comment by himadrisingh** [comment]
any update on this one.

**Comment by lkysow** [comment]
Hi Himadri,
Sorry for the delay. I've tried to replicate this issue however in my testing, the old node sticks around only until we perform a full sync which happens by default every 30s. This can be controlled via the flag:
```
  -consul-write-interval=<value>
     The interval to perform syncing operations creating Consul
     services, formatted as a time.Duration. All changes are merged and
     write calls are only made on this interval. Defaults to 30 seconds
     (30s).
```

After that period, the old node is deregistered.

**Comment by lkysow** [comment]
I'm going to close this for now since we haven't heard back but feel free to comment and we can reopen.
