### ISSUE TITLE
error="No cluster leader"

### ISSUE THREAD

**Issue by mohitmaheshwari31** [hashicorp/consul-k8s#1030]
We are trying to deploy consul in EKS(K8s version: 1.21) and we are getting the following error.

2022-02-11T06:46:03.894Z [WARN]  agent: (LAN) couldn't join: number_of_nodes=0 error="3 errors occurred:
	* Failed to resolve consul-server-0.consul-server.consul.svc:8301: lookup consul-server-0.consul-server.consul.svc on 172.20.0.10:53: no such host
	* Failed to resolve consul-server-1.consul-server.consul.svc:8301: lookup consul-server-1.consul-server.consul.svc on 172.20.0.10:53: no such host
	* Failed to resolve consul-server-2.consul-server.consul.svc:8301: lookup consul-server-2.consul-server.consul.svc on 172.20.0.10:53: no such host

"
2022-02-11T06:46:03.894Z [WARN]  agent: Join cluster failed, will retry: cluster=LAN retry_interval=30s error=<nil>
2022-02-11T06:46:08.621Z [ERROR] agent: Coordinate update error: error="No cluster leader"

Can someone please help us in this error ?

**Comment by t-eckert** [comment]
Hi @mohitmaheshwari31, can you please share the Helm values used to install Consul?

**Comment by mohitmaheshwari31** [comment]
@t-eckert .. I am using default values only. 
Just a question can it be related to EKS K8s 1.21 headless service, if yes Can you suggest some solution?

**Comment by t-eckert** [comment]
That could be! Can you try adding this label to the headless service?

`consul.hashicorp.com/service-ignore: true`

This will tell Consul to not create a Consul endpoint for this service. If 2 or more services point to the same pod deployment Consul can have issues resolving the endpoint.

**Comment by mohitmaheshwari31** [comment]
Still the same issue.

**Comment by lkysow** [comment]
Hi, can you provide exact instructions to reproduce please.

For example:

1. Create EKS k8s cluster with version 1.21
2. Run `helm install consul hashicorp/consul --version 0.40.0`

```
* Failed to resolve consul-server-0.consul-server.consul.svc:8301: lookup consul-server-0.consul-server.consul.svc on 172.20.0.10:53: no such host
```

These errors are saying that the Kube DNS entry for `consul-server-0.consul-server.consul.svc` isn't created.

**Comment by ishustava** [comment]
@mohitmaheshwari31 

It's normal to see these errors as Consul is coming up but they should eventually go away as the pods come up and the kube DNS can then resolve to the pod IPs.

Do you see that the errors repeat for a long time and the cluster never becomes healthy?

**Comment by mohitmaheshwari31** [comment]
Hi @ishustava @lkysow @t-eckert ,

Thank you so much for the input. 

Actually, we forgot to add endpointslices permission in coredns clusterrole.  
after updating the cluster role , it works fine.

**Comment by ishustava** [comment]
Glad you've figured it out! I'm going to close this issue for now.
