### ISSUE TITLE
consul-client pod is in pending state on newly added window node

### ISSUE THREAD

**Issue by sumit84mca** [hashicorp/consul-k8s#1043]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue
I have an EKS cluster. Initially there were linux nodes in the cluster. Recently I added a new Window node to the cluster. Now consul client pod is in pending state on window node. Here is the error message 

_MountVolume.SetUp failed for volume "kube-api-access-nt64l" : chown c:\var\lib\kubelet\pods\f685d14b-1022-4aa1-b276-6e0257f57bdb\volumes\kubernetes.io~projected\kube-api-access-nt64l\..2022_02_22_18_40_32.709771351\token: not supported by windows_

**Comment by ishustava** [comment]
Hey @sumit84mca 

I think this is an issue with Kubernetes on windows: https://github.com/kubernetes/kubernetes/issues/102849

**Comment by david-yu** [comment]
Hi @sumit84mca are you perhaps running Consul and/or Consul K8s using a custom built windows image out of curiosity?

**Comment by ishustava** [comment]
Hey @sumit84mca 

We haven't heard from you in a while. I'm going to go ahead and close this issue as it seems to be an issue with windows support on Kubernetes rather than consul-k8s. Please let us know if it's not the case and we can re-open.

**Comment by MageshSrinivasulu** [comment]
@sumit84mca Were you able to find any solution for it? Facing the same issue in AKS on Windows 2022 nodes
