### ISSUE TITLE
Require details on Consul's base Image

### ISSUE THREAD

**Issue by infa-svijayak** [hashicorp/consul-k8s#1055]
Hello Team,
We have currently deployed consul with version 1.8.4 in kubernetes and we have received few vulnerabilities from the consul image. It is a critical vulnerability and it states as follows

**libfetch before 2021-07-26, as used in apk-tools, xbps, and other products, mishandles numeric strings for the FTP and HTTP protocols. The FTP passive mode implementation allows an out-of-bounds read because strtol is used to parse the relevant numbers into address bytes. It does not check if the line ends prematurely. If it does, the for-loop condition checks for the '\0' terminator one byte too late.**

I was going through the consul docker images and figured that alpine images(or is it busybox?) are being used as the base image for docker and this vulnerability is found in the apk tools of the alpine image. I request details on the version of the alpine image which is being used in the consul docker image with version 1.8.4. Also I could see that the above mentioned vulnerability is fixed from alpine image version **3.14** and above according to https://github.com/alpinelinux/docker-alpine/issues/193. If you can let us know which version of consul image uses the base image version of alpine 3.14 and above will be helpful for us to upgrade our consul to that.

Thanks

**Comment by david-yu** [comment]
Hi @infa-svijayak for both the `hashicorp/consul` and the `hashicorp/consul-k8s` images you should be able to bump it to `alpine:3.15`. We don't maintain the `hashicorp/consul-k8s` image any longer as a note and Consul 1.8.x is also no longer maintained so there are potentially CVEs against Consul itself that may also need to be addressed through a Consul upgrade. I hope this helps.

**Comment by infa-svijayak** [comment]
Hi @david-yu,
Thanks for replying, can you let us know who maintains the hashicorp/consul-k8s images ?

**Comment by david-yu** [comment]
Hi @infa-svijayak our team had managed that repo previousl, however it is now superseded by `hashicorp/consul-k8s-control-plane`. We would also recommend upgrading your Consul K8s deployment as well as we no longer maintain `consul-k8s` images.

**Comment by david-yu** [comment]
Closing as I hope it answers your question. You may have already found this but our latest Dockerfile is located here: https://github.com/hashicorp/consul-k8s/tree/main/control-plane/build-support/docker
