### ISSUE TITLE
Behaviour of `consul.hashicorp.com/connect-service`

### ISSUE THREAD

**Issue by raphlcx** [hashicorp/consul-k8s#1097]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Hello, I would like to clarify the behaviour of `consul.hashicorp.com/connect-service` annotation.

On these few lines of comments:

https://github.com/hashicorp/consul-k8s/blob/879b0419325e74e265c43ea53230d7f1d1c27ce3/control-plane/connect-inject/annotations.go#L19-L21

It states if the annotation is not specified, the name of the first container will be used.

But, I believe when `consul.hashicorp.com/connect-service` annotation is not specified, it will now default to get the name of the Kubernetes Service associated to the Kubernetes pod right?

I have linked the doc in the section below on where I was coming from.

### Additional Context

https://www.consul.io/docs/k8s/annotations-and-labels#consul-hashicorp-com-connect-service

**Comment by ishustava** [comment]
Hey @raphlcx 

You are correct, we will default to the name of the Kubernetes service. We've created #1100 to fix the comment.

**Comment by raphlcx** [comment]
> Hey @raphlcx
> 
> You are correct, we will default to the name of the Kubernetes service. We've created #1100 to fix the comment.

Thanks for confirming!
