### ISSUE TITLE
Is exposing hostPort neccesary on the consul-client daemonset

### ISSUE THREAD

**Issue by TomHellier** [hashicorp/consul-k8s#1166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---
### Overview of the Issue

I run [kubescape](https://github.com/armosec/kubescape) against helm charts I'd like to deploy in my clusters.
> Kubescape is a K8s open-source tool providing a multi-cloud K8s single pane of glass, including risk analysis, security compliance, RBAC visualizer and image vulnerabilities scanning. Kubescape scans K8s clusters, YAML files, and HELM charts, detecting misconfigurations according to multiple frameworks (such as the [NSA-CISA](https://www.armosec.io/blog/kubernetes-hardening-guidance-summary-by-armo) , [MITRE ATT&CK®](https://www.microsoft.com/security/blog/2021/03/23/secure-containerized-environments-with-updated-threat-matrix-for-kubernetes/)), software vulnerabilities, and RBAC (role-based-access-control) violations at early stages of the CI/CD pipeline, calculates risk score instantly and shows risk trends over time.

I'm getting the following linting error:
```
<testcase
    classname="NSA"
    status="failed"
    name="Container hostPort"
    time="">
<failure
        message="Remediation: Avoid usage of hostPort unless it is absolutely necessary, in which case define appropriate exception. Use NodePort / ClusterIP instead. More details: https://hub.armo.cloud/docs/c-0044 apiVersion: apps/v1; kind: DaemonSet; namespace: default; name: consul-client" 
        type="Control"
    />
</testcase>
```
It looks like some [attempt was made in the past with restricting the number of hostPorts required](https://github.com/hashicorp/consul-k8s/commit/1f8a35759515ee6197368a42016ab4cb216aa3cb).

### Reproduction Steps

Template the helm chart using default values

### Logs
n/a

### Expected behavior
Unknown, afaik it isn't neccesary to expose these hostPorts on the cluster if you only want to use consul inside the cluster?

### Additional Context
https://hub.armo.cloud/docs/c-0044

Workloads (like pod, deployment, etc) that contain a container with hostport. The problem that arises is that if the scale of your workload is larger than the number of nodes in your Kubernetes cluster, the deployment fails. And any two workloads that specify the same HostPort cannot be deployed to the same node. In addition, if the host where your pods are running becomes unavailable, Kubernetes reschedules the pods to different nodes. Thus, if the IP address for your workload changes, external clients of your application will lose access to the pod. The same thing happens when you restart your pods — Kubernetes reschedules them to a different node if available.

**Comment by ishustava** [comment]
Hey @TomHellier 

Great question. Yes, we currently require it, and in our case it is necessary because otherwise there's isn't a good way to connect to the Consul clients deployed as a daemonset.

We are working on removing it, so stay tuned for those changes in the future!

**Comment by TomHellier** [comment]
Hi @ishustava, thanks for the reply.

I'm only using consul as a backend to vault while prototyping something at the moment so wasn't too sure either way. I'll add an exception to the rules I use for kubescape. Glad to hear you're working on removing that requirement

**Comment by wouter2397** [comment]
> Hey @TomHellier
> 
> Great question. Yes, we currently require it, and in our case it is necessary because otherwise there's isn't a good way to connect to the Consul clients deployed as a daemonset.
> 
> We are working on removing that requirement, so stay tuned for those changes in the future!

@ishustava Do you know if hostports are still required for the consul-client. We are also Consul users and looking into security risks here
