### ISSUE TITLE
consul/templates/server-statefulset.yaml:7:121): server.bootstrapExpect cannot be less than server.replicas

### ISSUE THREAD

**Issue by mariusmitrofan** [hashicorp/consul-k8s#1181]
### Overview of the Issue

HELM_VERSION=3.8.1
CONSUL_HELM_CHART=0.39.0

Custom values used:
replicas                = 3
bootstrapExpect = 5

Error that is being thrown by helm is:

```
Error: execution error at (consul/templates/server-statefulset.yaml:7:121): server.bootstrapExpect cannot be less than server.replicas
```

### Reproduction Steps

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.21.5-eks-bc4871b
- Cloud Provider: AWS EKS

**Comment by lkysow** [comment]
So are you planning on using multiple kube clusters with 3 servers in each? The Helm chart doesn't support this use case very well. It generally assumes one kube cluster per consul dc.

**Comment by mariusmitrofan** [comment]
Hi @lkysow ,

Maybe I wasn't clear.

I have *only one* kubernetes cluster, in which I deployed *only one* helm chart with *only one* dc.

Here's what I mean:

```
(plint) mariusmitrofan@Javier ~ (20:06:24) >> helm upgrade --install consul hashicorp/consul --namespace consul --version 0.39.0 --set server.replicas=5 --set server.bootstrapExpect=3

Release "consul" does not exist. Installing it now.

Error: template: consul/templates/server-statefulset.yaml:7:121: executing "consul/templates/server-statefulset.yaml" at <fail "server.bootstrapExpect cannot be less than server.replicas">: error calling fail: server.bootstrapExpect cannot be less than server.replicas          

```

Is this expected ?

I was assuming that I can deploy "5 servers" of Consul and set bootstrap to expect "only 3".

Isn't that...normal ?

**Comment by lkysow** [comment]
Ah okay, your original issue above swapped replicas and bootstrap expect:

> Custom values used:
replicas = 3
bootstrapExpect = 5

Hence the confusion.

I think we're following the docs recommendation here: https://www.consul.io/docs/agent/options#_bootstrap_expect

> This flag provides the number of expected servers in the datacenter. 

I don't recall exactly but I think if you set this to less than the correct number that you can run into issues with leadership/cluster membership/split brain.

**Comment by david-yu** [comment]
Closing as I believe the question was addressed. Please let us know if that is not the case!
