### ISSUE TITLE
Live updates to Consul catalog

### ISSUE THREAD

**Issue by sodabrew** [hashicorp/consul-k8s#1214]
I am using consul-k8s to sync the catalog from Kubernetes to Consul. This enables downstream applications to use Consul catalog and Consul DNS for service discovery.

This is a transitional state from a prior system based around Registrator. Two things have been lost in the transition and are causing pain at this time:

1. Registrator added and removed containers from Consul almost immediately. Consul-k8s operates on a 60s timer by default.
2. Registrator syncs healthchecks from appropriate environment variables. I haven't found the incantation for Consul-k8s to convey service healthchecks to Consul.

My question is: is there an operating mode for Consul-k8s to react to pod scheduling more quickly? Specifically I want to remove pods that are scheduled for eviction/termination, react quickly to pods that exit, and add pods that have started up sooner than the next 60s catalog sync tick.

Next steps may include using full Consul Mesh or eliminating Consul from the stack. But the intermediate stage right now needs to be stabilized against failures where e.g. during a rolling deploy it is possible for Consul to have all-dead containers for tens of seconds, resulting in application failures.

**Comment by david-yu** [comment]
Hi @sodabrew we have seen this request before as seen in https://github.com/hashicorp/consul-k8s/issues/1027. It is however a large change to catalog sync and we likely won't be addressing this any time soon. I will say that we are open to PRs if you are looking to address these issues and submit them for review.

As far as live updates to the catalog, using Consul Service Mesh is a better solution as we register and de-register services by watching the K8s API Server using our endpoints controller. This also ensures that mTLS communication is utilized for service to service communication and can be extended to multiple k8s clusters using either Admin Partitions or WAN Federation as per our docs.

**Comment by david-yu** [comment]
Closing as was addressed via previous response.
