### ISSUE TITLE
Clearer instructions in Helm chart notes on namespace

### ISSUE THREAD

**Issue by ChanderG** [hashicorp/consul-k8s#1224]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

On installation of the helm chart using a command described in the tutorials: https://learn.hashicorp.com/tutorials/consul/service-mesh-deploy, the Notes section in the helm output is slightly misleading.

### Reproduction Steps

Install the helm chart using a command like:
```
helm install -f ./config.yaml consul hashicorp/consul --create-namespace -n consul
```

### Logs

The output of the above command is something like this:
```
NAME: consul
LAST DEPLOYED: Tue May 17 05:41:23 2022
NAMESPACE: consul
STATUS: deployed
REVISION: 1
NOTES:
Thank you for installing HashiCorp Consul!

Your release is named consul.

To learn more about the release, run:

  $ helm status consul
  $ helm get all consul

Consul on Kubernetes Documentation:
https://www.consul.io/docs/platform/k8s

Consul on Kubernetes CLI Reference:
https://www.consul.io/docs/k8s/k8s-cli
```

### Expected behavior

Following the notes, running:
```
helm status consul
```

leads to a confusing error message:
```
Error: release: not found
```

I chanced upon the solution here: https://discuss.hashicorp.com/t/how-to-deploy-the-consul-client-on-k8s-with-custom-config-yaml/36602/4 which is as simple as running:
```
helm status -n consul consul
```

While this is partially an Helm issue (have opened one here: https://github.com/helm/helm/issues/10967), it will be better if the Notes section reflect the namespace flag in the helm commands correctly for newcomers if possible. I am not sure what information is available for use in the notes template, but even adding `-n <namespace>` will help.

### Environment details

Exact environment details don't really matter for this one. I see the Notes template on HEAD: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/NOTES.txt have the same format that I see.

Still:
```
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2+59bbb3530b6769", GitCommit:"59bbb3530b6769e4935a05ac0e13c9910c79253e", GitTreeState:"clean", BuildDate:"2022-05-13T06:43:45Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-2+59bbb3530b6769", GitCommit:"59bbb3530b6769e4935a05ac0e13c9910c79253e", GitTreeState:"clean", BuildDate:"2022-05-13T06:41:13Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jmurret** [comment]
Thank you @ChanderG!  great suggestion.  This has been addressed in [this PR ](https://github.com/hashicorp/consul-k8s/pull/1226).

**Comment by david-yu** [comment]
Thanks @ChanderG for the feedback we've addressed your feedback in our helm info display once Consul K8s is installed via Helm. This will be released in our next release of Consul K8s.
