### ISSUE TITLE
Expose Server Statefulset updateStrategy configuration

### ISSUE THREAD

**Issue by MeijerM1** [hashicorp/consul-k8s#1233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.
The Helm chart allows the configuration of the Consul Client updateStrategy. However the Server does not expose this configuration. The [official Consul K8s upgrade guide](https://www.consul.io/docs/k8s/upgrade) recommends updating the server pods one by one by decreasing the updatePartition amount. 
This process van be simplified by using the OnDelete strategy which reduces the need for multiple updates to the Helm chart.

#### Feature Description

Allow the server pod updateStrategy to be configured via the Helm chart.
#### Use Case(s)

Reduce the required effort when upgrading Consul.

**Comment by t-eckert** [comment]
Hi @MeijerM1,

Thank you for opening this issue. I think this makes a lot of sense and would be a great enhancement. I will share this with our PMs, @nrichu-hcp and @david-yu.

**Comment by david-yu** [comment]
No longer needed as we no longer need to utilize updatePartition due to this change: https://github.com/hashicorp/consul-k8s/pull/3000
