### ISSUE TITLE
sync kubernetes pod ips as consul services in consul

### ISSUE THREAD

**Issue by dineshba** [hashicorp/consul-k8s#126]
We have provision to sync kubernetes services as consul service. 
**Can we extend this feature to sync pod ips also to consul as consul service ?**

For our current use case, we are currently using [kube-consul-register](https://github.com/tczekajlo/kube-consul-register) to register the POD IPs to consul. Can we extend this feature in `consul-k8s`?

If this is valid extension, I would love to work on this feature and raise a PR.

**Comment by aswinkarthik** [comment]
In GKE, Pod IPs are treated as first class IPs i.e. Routes to Pod IPs are automatically added whenever new node is created.

In a single GCP, we have multiple GKEs across which communications happen directly between two Pods. Here we use Consul as the common catalog across these GKEs.

Would love this feature to be present.

**Comment by lkysow** [comment]
`ClusterIP` services have each of their endpoints (i.e. pod IPs) synced. Is your Service a different type?

**Comment by adilyse** [comment]
Since syncing of `ClusterIP` services using their pod IPs is available and there's been no further clarifications to the request, I'm going to close this for now. Please feel free to respond or open a new ticket if there was something we haven't addressed!
