### ISSUE TITLE
Adding podDistruptionBudget & podAntiAffinity on consul-injector-deployments

### ISSUE THREAD

**Issue by WJay-tec** [hashicorp/consul-k8s#1278]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

We have encountered issues where our consul-connect-injector pods are both evicted at the same time, most likely due to a scale down by `cluster-autoscaler`

#### Feature Description

This feature will help to make sure consul-connect-injector pods will always have at least 1 replica up and running, and at the same time have the injectors running in separate node to prevent the injectors from failing during the event of a nodal failure (Previous discussion in a separate issue https://github.com/hashicorp/consul-k8s/issues/1134)

#### Use Case(s)
This is applicable to all applications

#### Contributions
Yes

**Comment by david-yu** [comment]
@WJay-tec This sounds like a great feature. Would you be willing to contribute with a PR, there exists a podDisruptionBudget and podAntiAffinity config for servers in Consul K8s as an example.

**Comment by WJay-tec** [comment]
@david-yu sure will raise a PR for this thanks!

**Comment by WJay-tec** [comment]
Closing this issue as the PR is already merged

**Comment by david-yu** [comment]
@WJay-tec Thanks again for your contribution!
