### ISSUE TITLE
Consul helm chart recent switch for Envoy Proxy switched from alpine to Ubuntu.

### ISSUE THREAD

**Issue by pduboucher** [hashicorp/consul-k8s#1294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

More of a question, at most a half-bug.
In this commit https://github.com/hashicorp/consul-k8s/commit/ebf241f37ed751a8e45d9a938507eecf74f2c689
The image for EnvoyProxy moves from alpine to ubuntu in the initial configuration, and in the templates.

```
-     image: envoyproxy/envoy-alpine:v1.20.2
+     image: envoyproxy/envoy:v1.22.0
```

I was wondering what was the rational. 
I feel that alpine tends to be more security oriented, and has less vulnerabilities that need to be patched.
It's not a significant problem, since I will just overwrite the config with the envoy-alpine image, but I was wondering if I was missing something.

I can see that there is no 1.22.x version of envoyproxy/envoy-alpine available, so perhaps that is why.
Strangely, I did not find a reason why envoyproxy no longer has a -alpine version.

Is switching to ubuntu 1.22 preferable to -alpine 1.21.x?

**Comment by t-eckert** [comment]
Hi @pduboucher, we appreciate the question!

We made the decision to switch to the Ubuntu release for two reasons. The first is that the Envoy Alpine image is [no longer being released](https://github.com/envoyproxy/envoy/issues/19781) as the role that it served is now going to be served by the [distroless](https://hub.docker.com/r/envoyproxy/envoy-distroless) image. We will ultimately use the distroless release down the road, but until then, we are using the Ubuntu-based image to keep pace with Envoy releases.

You are more than welcome to replace this image with the latest Alpine-based release so long as 1.21 is supported by Consul.

**Comment by pduboucher** [comment]
Perfect, thanks for the explanation, I had missed the update that they were explicitly no longer supporting alpine long term.
