### ISSUE TITLE
found no secret of type 'kubernetes.io/service-account-token' associated with the consul-auth-method service account

### ISSUE THREAD

**Issue by kschoche** [hashicorp/consul-k8s#1295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue
When installing consul-k8s on Kubernetes 1.24+ I receive an error stating that no secret of type service-account-tokekn exists.

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  datacenter: "dc1"
  name: consul
  tls:
    enabled: true
    enableAutoEncrypt: true
  acls:
    manageSystemACLs: true
server:
  replicas: 1
connectInject:
  replicas: 1
  enabled: true
controller:
  enabled: true
```

1. View error
When installing Consul with ACLs enabled on Kind using Kubernetes 1.24+, I receive the following error:
```
NAME                                           READY   STATUS     RESTARTS      AGE
consul-client-4vmvn                            0/1     Init:0/1   1 (46s ago)   2m32s
consul-connect-injector-6888c7df56-8jjs8       0/1     Init:1/2   1 (12s ago)   2m32s
consul-controller-b84985c68-cmtsk              0/1     Init:1/2   1 (12s ago)   2m32s
consul-server-0                                1/1     Running    0             2m32s
consul-server-acl-init-5xh2p                   0/1     Error      0             102s
```

```
`$ kubectl logs -f consul-server-acl-init-5xh2p   | tail -n 2`
2022-06-20T20:47:12.574Z [ERROR] found no secret of type 'kubernetes.io/service-account-token' associated with the consul-auth-method service account
```

It appears that this behaviour is due to changes in Kubernetes token auto generation listed :
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes
```
The LegacyServiceAccountTokenNoAutoGeneration feature gate is beta, and enabled by default. When enabled, Secret API objects containing service account tokens are no longer auto-generated for every ServiceAccount. Use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API to acquire service account tokens, or if a non-expiring token is required, create a Secret API object for the token controller to populate with a service account token by following this [guide](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). (https://github.com/kubernetes/kubernetes/pull/108309, [@zshihang](https://github.com/zshihang))
```

### Expected behavior

Consul should run successfully on Kubernetes 1.24+

### Environment details

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.24.x
- Kind

### Workaround
My current workaround is to start Kind using the following command:
`kind create cluster --image kindest/node:v1.23.6`

**Comment by liggitt** [comment]
this is the same issue reported in https://github.com/hashicorp/consul-k8s/issues/1145

**Comment by kschoche** [comment]
duplicate of $1145
