### ISSUE TITLE
Write Consul Central Config on init from ConfigMap

### ISSUE THREAD

**Issue by nicholasjackson** [hashicorp/consul-k8s#136]
To leverage L7 features introduced in Consul 1.5 and 1.6 it would be nice to be able to specify central config in a config map and have this written to consul when the pod initializes.

For example given the following config map containing 3 elements of central config:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: central-config-split
data:
  1_web_defaults.hcl: |
    kind = "service-defaults"
    name = "web"
    protocol = "http"
  2_api_defaults.hcl: |
    kind = "service-defaults"
    name = "api"
    protocol = "http"
  3_api_resolver.hcl: |
    kind = "service-resolver"
    name = "api"

    # https://www.consul.io/api/health.html#filtering-2
    # # Show Node.Meta demonstration showing performance testing a new instance type
    default_subset = "v1"

    subsets = {
      v1 = {
        filter = "Service.Meta.version == 1"
      }
      v2 = {
        filter = "Service.Meta.version == 2"
      }
    }
```

I would like to add an annotation which would allow the init container for the pod to automatically write these to consul. For example the following annotation could be used:

```
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "api:9091"
        "consul.hashicorp.com/service-config": "central-config-split"
```

When the init container runs to inject the sidecar this configuration would automatically be written to Consul's central config.

*Questions:*
* Should connect inject be aware of changes to the config map and automatically write these to central config?
* Should the init container handle these details or should this be handled centrally by another controller?

**Comment by lkysow** [comment]
> Should the init container handle these details or should this be handled centrally by another controller?

I think handling this by another mechanism that's more centralizeed (maybe a sidecar to a server/client) would make more sense than having to annotate a random Connect deployment.

**Comment by nicholasjackson** [comment]
I agree, I think the controller also needs to be aware of changes to the config map. The only reservation is that config is often directly linked to an application stack. There would need to be a way of having multiple config maps handled by the controller. Ultimately this is starting to look like custom CRDs to give the most native K8s experience to the user.

SMI will support configuration of all our central config (working on this now) however this is abstracted from our core config format. As much a fan of SMI I am I think we probably need both approaches.

**Comment by lkysow** [comment]
Now that we have custom resource definitions this is the best way to control config entries (https://www.consul.io/docs/k8s/crds).
