### ISSUE TITLE
Consul k8s 1.22 not able to register service on consul via http request

### ISSUE THREAD

**Issue by vaibhavgulati** [hashicorp/consul-k8s#1369]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

**Comment by david-yu** [comment]
Hi @vaibhavgulati Could you provide more details in this issue on what you are experiencing and how to reproduce?

**Comment by david-yu** [comment]
Closing as no details were provided.
