### ISSUE TITLE
Two services with the same name but in different namespaces in k8s are mapped to a single service in consul

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#139]
consul-helm chart version: branch `master`
Deployed to AWS EKS

### Issue
If I create two services with the same name but in different namespaces in k8s, consul registers them as two instances under the same name.

For example, I have an ngnix service in the `default` and `foo` namespaces.
<img width="1680" alt="Screen Shot 2019-09-23 at 10 27 17 AM" src="https://user-images.githubusercontent.com/10640505/65448187-158c1380-dded-11e9-9c30-055223ef4fd5.png">

<img width="1674" alt="Screen Shot 2019-09-23 at 10 30 05 AM" src="https://user-images.githubusercontent.com/10640505/65448204-22a90280-dded-11e9-8d8b-148efcba3934.png">

Consul would then load balance between those two services if I use consul as DNS.
```
kubectl port-forward consul-consul-server-0 5000:8600 &
```
```
$ dig -p 5000 @127.0.0.1 +tcp nginx.service.consul

; <<>> DiG 9.10.6 <<>> -p 5000 @127.0.0.1 +tcp nginx.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47981
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nginx.service.consul.		IN	A

;; ANSWER SECTION:
nginx.service.consul.	0	IN	CNAME	ac0771705dcc411e997eb02853705779-27038583.us-east-2.elb.amazonaws.com.

;; ADDITIONAL SECTION:
nginx.service.consul.	0	IN	TXT	"external-source=kubernetes"
nginx.service.consul.	0	IN	TXT	"external-source=kubernetes"

;; Query time: 326 msec
;; SERVER: 127.0.0.1#5000(127.0.0.1)
;; WHEN: Mon Sep 23 10:38:13 PDT 2019
;; MSG SIZE  rcvd: 210


~:
$ dig -p 5000 @127.0.0.1 +tcp nginx.service.consul

; <<>> DiG 9.10.6 <<>> -p 5000 @127.0.0.1 +tcp nginx.service.consul
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2446
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nginx.service.consul.		IN	A

;; ANSWER SECTION:
nginx.service.consul.	0	IN	CNAME	a3f17333edcaf11e997eb02853705779-1573697906.us-east-2.elb.amazonaws.com.

;; ADDITIONAL SECTION:
nginx.service.consul.	0	IN	TXT	"external-source=kubernetes"
nginx.service.consul.	0	IN	TXT	"external-source=kubernetes"

;; Query time: 315 msec
;; SERVER: 127.0.0.1#5000(127.0.0.1)
;; WHEN: Mon Sep 23 10:38:15 PDT 2019
;; MSG SIZE  rcvd: 212
```

### Desired behavior
Sync should disambiguate between services deployed to different namespaces.

**Comment by filintod** [comment]
Yes this is true. I try to mitigate it by adding a tag for namespace so at least I can target it differently (kind of weird to put the namespace before the service name though) but don't see how this can get resolved as consul does not have a knowledge of namespaces unless it is added to consul code somehow.

**Comment by jasonliu747** [comment]
@lkysow Hey Luke, I think it really is a bug. The only workaround so far is by combining namespace and service name. Dose consul plan to officially support namespace?

**Comment by lkysow** [comment]
Hi @jasonliu747 yes it's on our roadmap to fix this.
