### ISSUE TITLE
Consul Connect: Application is unable to access other services until sidecar container is fully initialized

### ISSUE THREAD

**Issue by philslab-ninja** [hashicorp/consul-k8s#1397]
#### Question

I am using consul connect auto-injection.

If the sidecar container with envoy is not fully configured yet but the main application already issues a request over the network this request will fail and my application will not start.

I am using this workaround in my entrypoint.sh:

```
until [ $(curl --fail --silent --output /dev/stderr --write-out "%{http_code}" localhost:19000/ready) -eq 200 ]; do
  echo Waiting for proxy...
  sleep 1
done
```

With Istio there is the possibility to automatically add lifecycle hooks to the pod which take care of only letting the main container start when the istio sidecar container has sucessfully started.
This configuration option is called `holdApplicationUntilProxyStarts` - see: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

this can also be achieved using an annotation on the pod:
```
annotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
```

I have done some research but I am unable to find if an equivalent of this configuration is also available for consul connect.

Is there something like this available?
Any help would be greatly appreciated, THANKS! 

### Environment details

consul version: 1.12.0

**Comment by kschoche** [comment]
Hi @philslab-ninja - I do not believe that we have any hooks at the webhook level that would allow you to inject probes, but it looks like you could get away with adding a [readinessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) to your application which uses the same url that you mentioned in the issue?

It might look something like this:
```
readinessProbe:
  httpGet:
    path: /ready
    port: 19000
  failureThreshold: 1
  periodSeconds: 2   # (or some reasonable number)
```

Would that work for now? We have had some requests in the past to add the ability to inject lifecycle hooks through the injector but have not gotten to building it yet.

**Comment by narendrapatel** [comment]
Hi @kschoche,

I think the envoy admin port listens on localhost by default(also prefer to keep it that way). So don't think the above readinessProbe would work.
Something like `holdApplicationUntilProxyStarts` would be really helpful.
For us some of our apps are very high in traffic and received 100s of requests some times when the main app container is started and healthy but envoy is yet to start, causing connection refused errors. Its difficult to move to production with this.
A solution to this problem would be really helpful.

**Comment by kschoche** [comment]
Hi @alt-dima -

I just took a look at this again to see if there was an easier way to utilize the Envoy admin API to set a readinessProbe for the service directly, unfortunately its a bit complicated to setup while preserving any readinessProbes that were set by the user since Kubernetes only supports a single readinessProbe per container.
However, we do intend to support this in an upcoming release by setting our own readinessProbe to point to the active listener port of Envoy and I believe that *should* cover this use-case.

Stay tuned!
~Kyle

**Comment by junjie-landing** [comment]
Hi @kschoche , thx for the updated! This is a much needed feature. Is it included in the release any time soon?

**Comment by ilpianista** [comment]
If I've got this right, this is now supported in [consul-dataplane!239](https://github.com/hashicorp/consul-dataplane/pull/239), but consul-k8s is still missing the functionality as `StartupGracePeriodSeconds` is set to 0 by default and thus is never executed. I've opened [consul-k8s!3878](https://github.com/hashicorp/consul-k8s/pull/3878) which should allow to change that value to something else and enable the functionality.

**Comment by david-yu** [comment]
I'll go ahead and close this issue now that https://github.com/hashicorp/consul-k8s/pull/3878 is merged. Thank you @ilpianista . We will likely release this functionality in late May along with our scheduled patch releases.
