### ISSUE TITLE
[consul-k8s sync-catalog] Add a namespaceSelector option

### ISSUE THREAD

**Issue by HansK-p** [hashicorp/consul-k8s#140]
We have a K8s cluster where we would like different services in the cluster to be registered with different Consul datacenters, that is:
* myservice in the myservice-dev namespace should be registered in the dev datacenter
* myservice in the myservice-at namespace should be registered in the at datacenter
* ......

It is probably fairly easy to achieve this using the same pattern as is currently used for the connectInject plugin. Then we could specify a "namespaceSelector" for the sync-catalog process and label the myservice-dev, myservice-at, etc namespaces accordingly.

What would be needed to sync a service with the dev Consul data center would then be:
* Start consul-k8s sync-catalog with options:
  * -k8s-default-sync=false (or keep the default which is true)
  * -namespaceSelector="consul-datacenter=dev"
* Label the dev namespaces:
  * kubectl label ns myservice-dev consul-datacenter=dev
* Annotate the service:
  * consul.hashicorp.com/service-sync: "true" (if -k8s-default-sync is set to false)

',' can be used if there is a need to have more than one label in the namespaceSelector.

**Comment by david-yu** [comment]
Closing as we don't intend to support this use case in the short or longer term.
