### ISSUE TITLE
Is it possible to change consul client ports for consul-connect-inject-init

### ISSUE THREAD

**Issue by TambetP** [hashicorp/consul-k8s#1410]
#### Question

Hello. I am trying to get consul-connect working and ran into a problem. I would like to know if there is any way to change the consul client HTTP and grpc ports that are used in **consul-connect-inject-init** namely for `consul-k8s-control-plane connect-init`.  I am running Consul clients on different ports (http:8700,grpc:8702) and currently, I have not found any way to change these ports. 

### Current behavior

Currently, two environment variables are set in **consul-connect-inject-init** and used by `consul-k8s-control-plane connect-init`
export CONSUL_HTTP_ADDR="${HOST_IP}:8500"
export CONSUL_GRPC_ADDR="${HOST_IP}:8502"

This causes the init-container to fail in my set up.

### Environment details

- Kubernetes version: v1.22.8
- consul version: 1.12.3
- consul-k8s-control-plane version: 0.46.0
- envoy: 1.23.0

### Additional Context

I can see that the consul ENV variables for the init container are set here - https://github.com/hashicorp/consul-k8s/blob/53cb40d82ef4851a4a2b873bc9436cebc31dbb60/control-plane/connect-inject/container_init.go#L392-L393

Also `consul-k8s-control-plane connect-init` has the `-http-addr` option, but I have not found a way to add it to `consul-connect-inject-init` container command.

**Comment by kschoche** [comment]
Hi @TambetP - sorry for the late reply on this!
Unfortunately there is not a clean way to change the ports for the clients, we have a lot of infrastructure in place that is depends on these port values.

**Comment by TambetP** [comment]
@kschoche thanks for the answer. Are there any plans to make it configurable, since all the ports from the client side are?

While testing different ways how to get Consul Connect up and running in my environment I ran into another problem. Maybe you have some insight into that as well.
I tried getting Consul Connect running with the Consul client running on the Kubernetes host machine, not a container. Everything seemed to work fine except for service deregistration from the Consul. Any idea if it should be possible to get Consul Connect running with clients on the Kubernetes hosts?

**Comment by david-yu** [comment]
Hi @TambetP we don't have plans on making this configurable at the moment. We are planning on removing clients altogether from the mesh and instead manage the Envoy proxy via a separate component that retrieves Envoy config from consul server over XDS, which should remove these port requirements. This should happen later this year as part our next major Consul release.

**Comment by david-yu** [comment]
Closing.
