### ISSUE TITLE
UI options will not work in Consul version 1.6.X 

### ISSUE THREAD

**Issue by ADustyOldMuffin** [hashicorp/consul-k8s#1421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---
### Overview of the Issue

When deploying Consul into Kubernetes with Consul version 1.6.10 I encountered an issue saying the Config ui-config map could not be parsed. This is because the value in the config is `ui_config` which isn't valid for that Consul version (or below), and the existing ui field only has the ability for `ui: true`.

This causes other issues like being unable to scrape Consul for metrics using the helm chart, along with needing to modify the helm chart to be able to even use it for earlier versions of Consul.

### Reproduction Steps

Deploy Consul helm chart (current version) with the value `ui.enabled: true` and Consul version `1.6.10`.

Steps to reproduce this issue, eg:

1. When running helm install with the following `values.yml`:
```
global:
  image: consul:1.6.10
server:
  replicas: 1
ui:
  enabled: true
```

2. Observe Consul server never come up.

### Expected behavior

Consul helm chart would be compatible for all version of Consul the old helm chart was compatible with. I notice on the website that only Consul versions 1.11+ are listed, is the expectation that older versions of Consul just won't be supported at all?

**Comment by t-eckert** [comment]
Hi @ADustyOldMuffin, thank you for your question. Consul on Kubernetes supports the latest 3 versions of Consul. You are right that based on the [compatibility matrix](https://www.consul.io/docs/k8s/compatibility), version `1.11.x` is the oldest version we support.

Is there something that requires you to use Consul `1.6.10` in this case?

**Comment by ADustyOldMuffin** [comment]
Yes, we had old versions of Consul running on VMs and we're working to migrate to Consul K8s. We've been upgrading to get to newer versions, but this process is slow on VMs and we were hoping to go faster on K8s.

I've got it working now I was just looking for confirmation on the supported versions.

**Comment by t-eckert** [comment]
Great! Feel free to reach out as you work on upgrading if you have any questions.

**Comment by david-yu** [comment]
Hi @ADustyOldMuffin glad the compat matrix helped. I will go ahead and close.
