### ISSUE TITLE
failed to upgrade from 0.32.1 to 0.46.1(chart version)  

### ISSUE THREAD

**Issue by chenjinkai** [hashicorp/consul-k8s#1425]
### problem
consul  federation cluster upgrade from  0.32.1 to 0.46.1(chart version) , consul agent from 1.10.0 to 1.12.3. I upgraded master cluster firstly(every thing is ok), occurred problem as following when  upgraded  slaver cluster .

### logs 
1. consul-server-acl-init:
`[ERROR] Failure: creating acl binding rule for consul-k8s-component-auth-method-dc2: err="Unexpected response code: 500 (rpc error making call: cannot find auth method with name "consul-k8s-component-auth-method-dc2")"`

2. ingress gateway & terminating gateway & meshgateway & controller
`[ERROR] unable to login: error="Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)"`

**Comment by kschoche** [comment]
Hi @chenjinkai! Thanks for filing this issue and in sorry you're having trouble with the upgrade.
As there have been a few breaking changes between the two versions you're working with so I would recommend having a look at the changelog to isolate any changes that you may need to apply.
I think this particular issue may be that you might not have specified the k8sAuthMethodHost in your secondary values.yaml!

**Comment by chenjinkai** [comment]
> Hi @chenjinkai! Thanks for filing this issue and in sorry you're having trouble with the upgrade. As there have been a few breaking changes between the two versions you're working with so I would recommend having a look at the changelog to isolate any changes that you may need to apply. I think this particular issue may be that you might not have specified the k8sAuthMethodHost in your secondary values.yaml!

hi @kschoche thanks for reply.  After added k8sAuthMethodHost in secondary values.yaml,  still having the problem in controller & meshgateway

`[ERROR] unable to login: error="Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)"`

**Comment by chenjinkai** [comment]
@kschoche i added meshgateway and controller binding-rule in master cluster,using command `consul acl binding-rule create`. after restarted the controller and meshgateway  pod, then everything looked like ok.

**Comment by kschoche** [comment]
Hi @chenjinkai Thanks for the follow-up, I'm glad you got it working!

I'll go ahead and mark this closed, if you run into additional trouble please feel free to open a new issue!
