### ISSUE TITLE
Can we have support for EKS with Fargate Node Groups

### ISSUE THREAD

**Issue by ssala7** [hashicorp/consul-k8s#1434]
Can we have support for EKS with Fargate Node Groups.
Fargate does not support daemon sets for client installation.

**Comment by david-yu** [comment]
Hi @ssala7 we are working towards removing daemonsets for the default deployment of Consul K8s, which is aligned with our next major Consul release. We'll let you know later this year when a beta is available to try out.

**Comment by david-yu** [comment]
Closing since we now have support for EKS Fargate with Consul K8s 1.0.0-Beta, our GA is scheduled for next month.
