### ISSUE TITLE
ability to create service definition also for agents

### ISSUE THREAD

**Issue by bilalcaliskan** [hashicorp/consul-k8s#1436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.
No, actually my problem here is about a missing feature actually.

#### Feature Description
The feature request i mention is that, ability to create Kubernetes Service object for clusters which only use Consul agents as client. 

#### Use Case(s)
Assume that you are using a central Consul cluster outside of Kubernetes, on virtual machines. But you also have 100+ Kubernetes clusters. You are actively using sync-catalog to register/deregister Kubernetes services into Consul. You also have couple of custom operators which interact with Consul through Consul client which is located on each of the nodes in Kubernetes. 

We are planning to remove Consul clients from worker nodes inside Kubernetes since we have lots of Kubernetes clusters. This will benefit our Consul clusters from resource consumption point of view. But without the ability of creating Service object for client-only Consul installations through Helm, any custom solution which uses Consul client will fail. 

As you see [in here](https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/expose-servers-service.yaml#L3), this condition blocks that behavior if our installation is not on server mode.

**Comment by kschoche** [comment]
Hi @bilalcaliskan  -
Thanks for filing this issue and raising it to our attention and sorry for the late reply.

We are currently working on a [large change to the architecture ](https://github.com/hashicorp/consul-k8s/issues/1438 
) of `consul-k8s` which will remove the client agents altogether. I believe that your feature request would be entirely covered by our changes that are landing soon, namely in removing clients and allowing the use of `externalServers` with `syncCatalog` you should be able to accomplish what you described!

Stay tuned, but feel free to reach out here, or on the linked issue https://github.com/hashicorp/consul-k8s/issues/1438 
 if you have additional feedback or questions.
Cheers,
~Kyle

**Comment by bilalcaliskan** [comment]
thanks for your detailed explanation @kschoche, i am closing the issue now. Cheers!
