### ISSUE TITLE
Helm chart wrong value in _helpers.tpl for consul.pdb.connectInject.maxUnavailable

### ISSUE THREAD

**Issue by andriktr** [hashicorp/consul-k8s#1529]
Hi, 
Noticed that section in `_helpers.tpl` fiekl contains contains wrong value in `consul.pdb.connectInject.maxUnavailable`
```yaml
{{- define "consul.pdb.connectInject.maxUnavailable" -}}
{{- if eq (int .Values.connectInject.replicas) 1 -}}
{{ 0 }}
{{- else if .Values.connectInject.disruptionBudget.maxUnavailable -}}
{{ .Values.server.disruptionBudget.maxUnavailable -}} <- Should be changed to {{.Values.connectInject.disruptionBudget.maxUnavailable}}
{{- else -}}
{{- if eq (int .Values.connectInject.replicas) 3 -}}
{{- 1 -}}
{{- else -}}
{{- sub (div (int .Values.connectInject.replicas) 2) 1 -}}
{{- end -}}
{{- end -}}
{{- end -}}
```
As result if we set `connectInject.disruptionBudget.maxUnavailable` in `values.yaml` this has no effect.

**Comment by kschoche** [comment]
Hi @andriktr - Thank you for bringing this to our attention and sorry for the inconvenience! I've pushed the fix and it should be in our next release!
Cheers,
~Kyle
