### ISSUE TITLE
Commas in Service tags cannot be escaped

### ISSUE THREAD

**Issue by erdanzhang** [hashicorp/consul-k8s#1531]
### Community Note 
Per document: 
https://www.consul.io/docs/k8s/annotations-and-labels

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/84437068/192314153-a99c72f8-2d78-4515-a257-61de95f63ae3.png">

Commas in service tags should be able to be escaped by "\". However, when using the K8S deploy template and enabling service mesh (sidecar injection)

```
template:
    metadata:
      annotations:
        consul.hashicorp.com/service-tags: mid\,dle,com\,ma
```

The service tag got through Consul API endpoint:

```
{
    "test-svc": [
        "dle",
        "com\\",
        "ma",
        "mid\\"
    ],
}
```

### Reproduction Steps

Installing Consul helm chart, enable connect inject. And deploy a service by adding the annotation above. By using the Consul catalog API endpoint, we should able to see the reproduced result.

### More Context
A similar issue has been address in here:
https://github.com/hashicorp/consul-k8s/issues/719

And a merged PR:
https://github.com/hashicorp/consul-k8s/pull/983

**However, the merged code ONLY parses the services tag when running the command sync-catalog` not in the controller `inject-connect`.**

A possible reasonable solution is to add the following line in `control-plane/connect-inject/endpoints_controller.go:1215` to `consulTags` function:

```
// consulTags returns tags that should be added to the Consul service and proxy registrations.
func consulTags(pod corev1.Pod) []string {
	var tags []string
	if raw, ok := pod.Annotations[annotationTags]; ok && raw != "" {
		tags = append(tags, parseTags(raw)...)
	}

// Redefine parseTags here or move control-plane/catalog/to-consul/resource.go: parseTags to a common util library
func parseTags(tagsAnno string) []string {
```

**After I made the chaand nge as mentioned above, deploy the image to my k8s cluster, the service tag can now be correctly spilited**

@lkysow Hey, [Luke Kysow](https://github.com/lkysow), PR https://github.com/hashicorp/consul-k8s/issues/719 seems to be authored by you, could you please take a look at this issue, and decide if the proposed solution is reasonable? Many thanks!

This is current the blocker for our team to onboard using Consul :)

**Comment by kschoche** [comment]
Hi @erdanzhang - Thanks for raising this issue to our attention, I've merged the fix into our main branch and it should be part of our upcoming release.
Cheers.
~Kyle

**Comment by erdanzhang** [comment]
@kschoche Thanks for the quick respond and nice fix!!! Look forward to the next release and Consul onboarding!!!
