### ISSUE TITLE
Support TLS for servers and clients

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#154]
As part of hashicorp/consul-helm#137, we will be adding TLS to the Consul Helm chart, however a number of tasks that are part of the chart won't work without corresponding changes in the consul-k8s repo. 

Here is a list of areas that we'll need to change to support TLS (this list is not comprehensive):
- Sync Catalog (it uses a Consul client when syncing in both directions)
- ACL bootstrapping, i.e. `server-acl-init` command
- Connect Inject

**Comment by grove-mountain** [comment]
Hulu asked for this as well.

**Comment by lkysow** [comment]
Should we close https://github.com/hashicorp/consul-k8s/issues/79 and track TLS here?

**Comment by lkysow** [comment]
Also there's a [PR](https://github.com/hashicorp/consul-k8s/pull/30) for adding connect inject TLS support.

**Comment by ishustava** [comment]
@lkysow yeah I think we should track it here because #79 is specific to connect-inject.

**Comment by mxplusb** [comment]
What is #79 still blocked on? That PR has been open for a long time and this is definitely a much needed feature.

**Comment by epd** [comment]
Hi all - just updated PR #30 and added some additional tests. Would appreciate some :eyes:

**Comment by ishustava** [comment]
This is fixed in #137 and all the changes shipped in consul-helm [`v0.16.0`](https://github.com/hashicorp/consul-helm/releases/tag/v0.16.0).
