### ISSUE TITLE
Health checks, Kubernetes probes and Connect

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#155]
Currently the Consul Connect integration doesn't hook into Kubernetes health/liveliness probes nor do we provide a way to register Consul health checks. Thus when a Pod goes unhealthy we still route to it.

**Comment by pbusko** [comment]
We're experiencing the same issue here, in our use case TCP health check is not enough. Without integration with k8s readiness/liveness probes requests are frequently being routed to dead pods.

**Comment by lkysow** [comment]
Thanks Pavel, what do you think about us automatically hooking into the kube readiness probes?

**Comment by pbusko** [comment]
Thanks for your response @lkysow .

Readiness probe hook would be the best option imo. Liveness probe by it's nature doesn't guarantee that pod is ready to accept traffic (at least not always) while readiness probe hook could help to leverage native k8s capabilities without need to duplicate health checks (k8s + consul). Also in such case when not all services deployed in kubernetes are connect-enabled this approach allows to keep consistent way of health check definitions.

**Comment by lkysow** [comment]
Health checks have now been released! We now sync Kubernetes probes to Consul. See https://www.consul.io/docs/k8s/connect/health. This was released in consul-helm v0.26.0.
