### ISSUE TITLE
Lost and don't reconnect app after consul client pod died

### ISSUE THREAD

**Issue by Veres72** [hashicorp/consul-k8s#161]
My installation: 
kubernetes v1.14.3
consul within kubernetes cluster v1.6.1
consul connect with consul-k8s v0.9.0
I enabled HostNetwork: true for accessing my connect sidecars to my consul client on worker nodes.
Problem: 
If consul client pod are dead and recreate, all pod with consul connect on this worker lost and don't reconnect to consul. All connections from this app to another app through consul connect didn't work. 
How reproduce: 
Install consul connect via helm and enable HostNetwork: true for consul client. Deploy several apps with consul connect and delete consul client pod.

**Comment by lkysow** [comment]
Hi @Veres72 , the latest version of the consul-helm chart (v0.14.0) supports a `client.dataDirectoryHostPath` config that will mount Consul's data on the host disk. When the agent restarts, it will re-register its services. If you use that, be sure to also be running with PodSecurityPolicies so other Pods can't mount the same hostPath.

We're working on a better fix via a sidecar that will re-register the Pod if it is deregistered. Watch https://github.com/hashicorp/consul-k8s/issues/171 for that.

**Comment by lkysow** [comment]
This is fixed in consul-helm v0.15.0
