### ISSUE TITLE
consul server rollout restart causes downtime

### ISSUE THREAD

**Issue by yalctay93** [hashicorp/consul-k8s#1612]
#### Question
Hello, we are running consul server in version 1.13.2 as a `StatefulSet` in our on prem k8s cluster with the version v1.23.x.
We have noticed a weird behaviour when executing `kubectl rollout restart statefulset consul-server`.
We would expect the `StatefulSet` to restart the pods one by one however, it looks like the pods are failing due to leader election and thus it causes a downtime of the service. It takes ~ 5 minutes until the pods recover from this state and negotiate a new leader.
Is this behaviour expected? Is there anything we can do to improve?

### CLI Commands (consul-k8s, consul-k8s-control-plane, helm)

`kubectl rollout restart statefulset consul-server`

### Helm Configuration
We have the standard configuration in place, nothing fancy.

### Steps to reproduce

Deploy consul on k8s as a `StatefulSet` and trigger a new rollout of the pods, or just use `kubectl rollout restart statefulset consul-server` command. 

### Expected behaviour
Pods should be restarted one by one.

### Current behaviour
Pods are failing due to multiple errors, see logs of one of the pods.
[logs.txt](https://github.com/hashicorp/consul-k8s/files/9763491/logs.txt)

**Comment by darkn3rd** [comment]
I think I have seen this behavior before, but I have not troubleshooted this more deeply.  I wonder if this is related to https://discuss.hashicorp.com/t/unstable-deployment-on-k8s-with-helm-chart/44411

**Comment by yalctay93** [comment]
> I think I have seen this behavior before, but I have not troubleshooted this more deeply. I wonder if this is related to https://discuss.hashicorp.com/t/unstable-deployment-on-k8s-with-helm-chart/44411

Perfect - that has solved the issue. Thank you alot!

**Comment by lkysow** [comment]
Fixed by #3000
