### ISSUE TITLE
Unable to upgrade servers first when going through version 0.40.0 of helm chart

### ISSUE THREAD

**Issue by takeda** [hashicorp/consul-k8s#1622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

In version 0.40.0 a change (https://github.com/hashicorp/consul-k8s/pull/1000) introduced that adds "-client" to DaemonSet. Unfortunately that renders updateStrategy: OnDelete (as recommended on https://developer.hashicorp.com/consul/docs/k8s/upgrade#upgrading-consul-servers) useless as the old DaemonSet is being removed due to name change.

Is there a workaround?

### Reproduction Steps

Upgrade from 0.38.0 to 0.47.1 following steps listed on https://developer.hashicorp.com/consul/docs/k8s/upgrade#upgrading-consul-servers

**Comment by david-yu** [comment]
Sorry for the troubles with the upgrade. We only intend on introducing breaking changes between minor versions and not patch releases moving forward. We also now have release notes for consul-k8s as shown here: https://developer.hashicorp.com/consul/docs/release-notes/consul-k8s/v1_2_x
