### ISSUE TITLE
Incorrect assumption of StatefulSet name in server-acl-init

### ISSUE THREAD

**Issue by sbuzonas** [hashicorp/consul-k8s#165]
Wasn't sure if this was better reported in hashicorp/consul-helm or here

The `server-acl-init` subcommand assumes that the name of the StatefulSet will be `{release_name}-consul-server`

https://github.com/hashicorp/consul-k8s/blob/master/subcommand/server-acl-init/command.go#L143

The helm chart allows a user to specify a fullname override.
https://github.com/hashicorp/consul-helm/blob/v0.12.0/templates/_helpers.tpl#L8

Given the following configuration values.yaml provided to helm:
```
fullnameOverride: consul
global:
  bootstrapACLs: true
```

The StatefulSet will be named `consul-server` and the bootstrap job will fail

**Comment by sbuzonas** [comment]
Created hashicorp/consul-helm#286 as a fix likely require updates to both

**Comment by lkysow** [comment]
This is fixed in consul-helm v0.15.0. Thanks!
