### ISSUE TITLE
Registration of services in the Consul via inject side-car with ExternalIP Ingress Controller

### ISSUE THREAD

**Issue by nightguide** [hashicorp/consul-k8s#175]
We use the consul-connect service-mesh solution in our Kubernetes cluster with the ingress Ambassador. Now services are registered in Consul SD with POD IP. If I try to access this service from the local network (outside the kubernetes cluster) then this service will be unreachable.
And this is logical since the service is registered with POD IP, and the PODS network is available only inside the Kubernetes cluster.

Based on this, I have a question:

How to register services with the IP address of the ingress controller, through which annotation can this be done?

I will explain. We want to register services with the External IP address of the ingress controller so that all incoming traffic from the local network to the kubernetes cluster is routed through ingress.

One solution for becoming a reachable registered service is to use CNI Plugin - “Calico”, but I don’t want to use it.

**Comment by lkysow** [comment]
Hi, since you've also asked in our discuss forum, we'll answer you there since that's the preferred space for questions (https://discuss.hashicorp.com/t/registration-of-services-in-the-consul-via-inject-side-car-with-externalip-ingress-controller/4528)
