### ISSUE TITLE
consul k8s vmbox registers wrong network adapter

### ISSUE THREAD

**Issue by avishaiNB** [hashicorp/consul-k8s#185]
Hi,

**Setup**
- Oracle VM VirtualBox v6.0.12 r133076 (Qt5.6.2)
- On the VM i created Ubuntu, 18.04.3 LTS (Bionic Beaver) machine.
- configured with:
NAT (for internet connection)
Host-only (for duplex communication VM <--> Host)
so now i have two IPs: 
enp0s3: (NAT, has internal IP 10.0.2.15) 
enp0s8: (Host-only has the static node ip 192.168.56.100)

- netplan configuration:
network:
  version: 2
  ethernets:
    enp0s3:
      addresses: []
      dhcp4: yes
      optional: true
    enp0s8:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.56.100/24]
      nameservers:
        addresses: [192.168.2.100, 192.168.2.101]

- Installed kubeadm with calico as pod network on the VM.

**Installed Helm Charts:**
*consul*
image: consul:1.6.2
imageK8S: hashicorp/consul-k8s:0.10.1

up to here every thing work perfectly.

when i deploy some other chart, for example rabbit, i noticed that it registers the service with the 
internal NAT IP (10.0.2.15), and not with the external static IP (192.168.56.100).

can i manually point consul to register the external static ip (interface enp0s8) ?
10x!

**Comment by avishaiNB** [comment]
**Solution**
- Add **--node-ip=192.168.56.100** to **/etc/systemd/system/kubelet.service** file under **KUBELET_CONFIG_ARGS**.

- Restarted kubelet with:
```
systemctl daemon-reload
systemctl restart kubelet
```

This actions changed the cluster internal ip to use the Host-only adapter ip, 
making the consul use that ip instead the NAT's one.

That change got me to the desired result. :) :)

**Comment by lkysow** [comment]
Nice! Should I close this then?

**Comment by avishaiNB** [comment]
> Nice! Should I close this then?

Yes, everything seems to work great.
