### ISSUE TITLE
1.0.3 release: not available for helm install

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul-k8s#1863]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

I can see that v1.0.3 has been released on github, but it's not available in the helm repo:

### Reproduction Steps

Following the instructions on installation:

1. Run:
```
$ helm repo add hashicorp https://helm.releases.hashicorp.com
$ helm repo update
$ helm search repo hashicorp/consul -l
```

Only yields v 1.0.2

```
$ curl https://helm.releases.hashicorp.com/consul-1.0.3.tgz
```

yields a 404

but

```
https://helm.releases.hashicorp.com/consul-1.0.2.tgz
```

downloads the package as expected

**Comment by curtbushko** [comment]
Hello @mr-miles,

Thanks for sending us a message. We are having some difficulties with helm chart publishing at this time and are waiting on an internal team to fix it. 

I currently do not have an ETA on when it will be fixed.

**Comment by david-yu** [comment]
Hi @mr-miles 1.0.3 is out but we are still having some issues with 0.49.3. We anticipate to have all the releases by end of the week. Closing this out for now.
