### ISSUE TITLE
no github notifications with your releases

### ISSUE THREAD

**Issue by hihouhou** [hashicorp/consul-k8s#189]
Hello,

Notification enabled for hashicorp/consul-k8s about release (see joined file) but nothing received...
![github com_hashicorp_consul-k8s_releases](https://user-images.githubusercontent.com/10907233/72201169-93823200-3451-11ea-9a38-4338e1878c2d.png)

hashicorp/terraform  and hashicorp/packer notifications about releases works, could you enable it for this repository ?

Regards

**Comment by lkysow** [comment]
Hi @hihouhou,
We don't do releases for `consul-k8s`, just git tags. However we do use releases for [consul-helm](https://github.com/hashicorp/consul-helm) and we always do a consul-helm release following consul-k8s so I would suggest subscribing to releases in that repo.

**Comment by hihouhou** [comment]
ok, thank you
