### ISSUE TITLE
Getting Service Mesh metrics onto prometheus

### ISSUE THREAD

**Issue by revanthalampally** [hashicorp/consul-k8s#190]
Tried adding this particular config using consul cli
`{
    "Kind": "proxy-defaults",
    "Name": "global",
    "Config": {
        "envoy_dogstatsd_url": "udp://127.0.0.1:9125",
        "envoy_stats_flush_interval": 10,
        "prometheus_bind_addr": "0.0.0.0:9102"
    }
}`
But I do not see this config being injected into the sidecar. I have also tried restarting the injector pod just in case.
Does anyone know how/when the new config would be picked?

**Comment by lkysow** [comment]
This is now supported in consul-helm v0.31.0. See https://www.consul.io/docs/k8s/connect/observability/metrics for docs.
