### ISSUE TITLE
Add support for JSON output

### ISSUE THREAD

**Issue by joshwolfer** [hashicorp/consul-k8s#2012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
---

#### Is your feature request related to a problem? Please describe.

Not related to a problem. 

#### Feature Description

I would like to be able to take the output from certain commands and easily consume it to be re-usable. For example:

```
$ consul-k8s proxy list -n unicorn
Namespace: unicorn

Name                            Type
unicorn-frontend-97848474-mkczg Sidecar
```

I would like to have the output presented in json so I can quickly resolve the proxy list and then do additional things.

Similar to how kubectl does it: 
consul-k8s proxy list -n unicorn -o json

#### Use Case(s)

Explained above

**Comment by david-yu** [comment]
Closed by https://github.com/hashicorp/consul-k8s/pull/3221
