### ISSUE TITLE
SHA Mismatch on Brew Formulae

### ISSUE THREAD

**Issue by reskin89** [hashicorp/consul-k8s#2017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Overview of the Issue

the SHA256 in the brew formulae doesn't seem to match the zip provided when installing via brew:

```shell
➜  brew tap hashicorp/tap
➜  brew install hashicorp/tap/consul-k8s
==> Downloading https://releases.hashicorp.com/consul-k8s/0.49.0/consul-k8s_0.49.0_darwin_arm64.zip
######################################################################## 100.0%
Error: consul-k8s: SHA256 mismatch
Expected: 6d911c6ed1293be3d29720abc9122d33ba3065639c3d3ff81d1355aec564c59f
  Actual: f9112db9f2229233067c05ed231d47db803283a7ebef66d89885eaf1ea0a2ec4
    File: /Users/reskin89/Library/Caches/Homebrew/downloads/4b929008b8f601dc227c98d99f3164c9c641bb2b85d73ddb3fd9455cd276267a--consul-k8s_0.49.0_darwin_arm64.zip
To retry an incomplete download, remove the file above.
```

### Reproduction Steps

use the brew installation method on an M1 Mac.

**Comment by david-yu** [comment]
Hi @reskin89 does this work after you do a `brew update`? I tried this myself and it seems to work ok.

**Comment by david-yu** [comment]
Closing due to no response. Let us know if you have further issues!
