### ISSUE TITLE
https://helm.releases.hashicorp.com/ points to archived repo.

### ISSUE THREAD

**Issue by ww-83** [hashicorp/consul-k8s#2025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Feature Description

Official helm repo points to archived git repo. https://github.com/hashicorp/consul-helm. Can this be updated to use the current repo as helm chart here supports later versions of K8s cluster and higher versions of Consul.

**Comment by david-yu** [comment]
Thanks for reporting, the repo url should now point to the correct place for where the charts are located.
