### ISSUE TITLE
Consul with EKS Fargate (100%)

### ISSUE THREAD

**Issue by pdtec-ivisilva** [hashicorp/consul-k8s#2045]
#### Question

I am trying to deploy helm charts in K8s (EKS with Fargate compute type). My question is, is it possible to deploy consul in EKS Fargate?

And how can I change scheduler from default-scheduler to fargate-scheduler?

### Helm Configuration

I am using default Helm charts and not custom helm charts.

### Current understanding and Expected behavior

I would like that consul works in the EKS Fargate becuase it is showing this error:

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  3m28s (x7 over 33m)  default-scheduler  0/2 nodes are available: 2 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.

### Environment details

- Helm Charts version: 1.11
- Kubernetes version: 1.25
- Cloud Provider: AWS EKS Fargate

**Comment by david-yu** [comment]
@pdtec-ivisilva Could you share your values.yaml file? You should be able to deploy on EKS Fargate if you set `connectInject.transparentProxy.defaultEnabled` to false. Currently EKS Fargate does now allow `CAP_NET_ADMIN` privileges but I believe that will change later this year.

**Comment by david-yu** [comment]
Closing as no response was given. Please feel free to open a new issue.
