### ISSUE TITLE
Add support for idleTimeout on Service Router

### ISSUE THREAD

**Issue by kphatak** [hashicorp/consul-k8s#2153]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

In consul helm, the Service Router spec missing support for `idleTimeout` parameter which was introduced in 1.14 (Dec 2022)
GH issue related to feature: https://github.com/hashicorp/consul/issues/14340
 Developer doc: https://developer.hashicorp.com/consul/docs/v1.14.x/connect/config-entries/service-router#idletimeout

#### Feature Description
Hashicorp docs mention the parameter but the service router spec does not include `idleTimeout` parameter.

#### Use Case(s)

Hashicorp support recommended setting up this parameter on our consul cluster as we were seeing some timeouts on our upstream connection.

**Comment by david-yu** [comment]
@kphatak Thank you for filing this issue. It is on our backlog but was not prioritized so thank you for bringing it to our attention.

**Comment by david-yu** [comment]
Closing as this is now merged. Thank you @kphatak!
