### ISSUE TITLE
Graceful shutdown consul deletion

### ISSUE THREAD

**Issue by anasokan** [hashicorp/consul-k8s#219]
There is a case of graceful shutdown of a POD that has consul configured is required. This can be an enhancement in consult-k8's
Here the expectation is 
1. Other services are using consul as serivce mesh to connect to this Pod.
2. When Pod  is deleted, Pod should not receive new load and serve the old existing request(which takes some time) and then die.
3. For this as first step when Pod is deleted before even sending SIGTERM to Pod process, the consul node deletion should happen. Maybe a new annotation could be introduced to give this behavior.

**Comment by filintod** [comment]
that already happens if you use the [helm chart](https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L172), consul sync is mainly doing syncing of service and acl setup. Not sure you have another use case in mind?

**Comment by lkysow** [comment]
@anasokan are you still seeing this behaviour? When the pod shuts down the `preStop` hook should be deregistering the service which should stop further requests.

**Comment by lkysow** [comment]
Closing because we haven't heard back.
