### ISSUE TITLE
Feature request: sidecar injection based on namespace annotations

### ISSUE THREAD

**Issue by krancour** [hashicorp/consul-k8s#22]
One thing I'd be really interested in seeing is things move in a direction that further minimizes the degree of Consul-awareness that a pod must have.

I think one, relatively easy thing that can move the needle on that is an option to inject proxy sidecars on the basis of annotations on the _namespace_ as an alternative to the pod annotations that are already supported.

Why?

It's quite a realistic scenario that a cluster operator / admin / superuser is responsible for creating namespaces as sandboxes for other teams (wherein they might define the permissions that different roles within that team have with respect to that namespace). The point, however, is that with an _operator_ responsible for the namespace, honoring annotations on the namespace means an _operator_ can effectively (and selectively) enforce the use of the service mesh as a matter of policy rather than requiring that all teams conform, which is harder to enforce.

**Comment by freeseacher** [comment]
for now i'm experimenting with k3s with their local-host-path provisioner for volumes. 
I'd add consul-sidecar and launch installation of postgres helm chart. 
I'm was pretty disappointed with postgres can't up. during some debug i was drownd to know how that local-host-provisioner is actually works. it looks like a controller in namespace local-path-storage and upon recieving request to create volume it spawns pod with busybox that actually create volume and reports job done to controller
ofcause proxy was injected automatically. ofcause after that it can't report to controller job is done. 

it is defenetly a good idea to inject sidecars on specially marked namespaces not all of them.

**Comment by david-yu** [comment]
Hi there, this is an old issue but I wanted to follow up here. Although annotations for handling namespace connect injection is not explicitly supported we do have a few options to help with injecting pods within a set of namespaces. Namely [connectInject.k8sallownamespaces](https://www.consul.io/docs/k8s/helm#v-connectinject-k8sallownamespaces) and [connectInject.k8sdenynamespaces](https://www.consul.io/docs/k8s/helm#v-connectinject-k8sdenynamespaces). I'll go ahead and close this issue now, but please go ahead and re-open if you feel this does not address the use case of connect injecting or disallowing connect inject in specific namespaces.
