### ISSUE TITLE
how to find k8s consul acl token 

### ISSUE THREAD

**Issue by lanyuange** [hashicorp/consul-k8s#221]
/ # cat consul/aclconfig/acl-config.json 
{
  "acl": {
    "enabled": true,
    "default_policy": "deny",
    "down_policy": "extend-cache",
    "tokens": {
      "agent": "e3ec62bc-3737-8d32-1c21-da641c2d9e8c"
    }
  }

the token do not use

consul logs
020/03/01 12:55:22 [ERR] http: Request GET /v1/acl/tokens?dc=dc1, error: Permission denied from=172.20.2.240:45516

I try to do  use api to create it  but falied  

[root@k8s01 consul-helm]# curl -H "X-Consul-Token: secret"  -X PUT -d '{"Name": "dc1", "Type": "management"}'  http://192.168.1.60:8500/v1/acl/create?token=e3ec62bc-3737-8d32-1c21-da641c2d9e8c 
rpc error making call: Permission denied

Can you tell me how to deal with it？Thinks.

**Comment by lkysow** [comment]
Hi, did you fix this?

**Comment by lanyuange** [comment]
yes thinks.
