### ISSUE TITLE
Pods in service mesh lose connectivity to other services, connect-inject

### ISSUE THREAD

**Issue by mw-uws** [hashicorp/consul-k8s#2218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Consul is installed via helm using the values below. Multiple services (hashicorp vault, also installed via helm, around 20 custom microservices) are running, spread over several namespaces, external services are connected via a terminating gateway (postgres, mysql)
The custom services are configured to use rotating database credentials supplied by vault.

Right after bootstrapping consul and all services, everything is working as expected.

The issue begins after the mesh is running for some time: random service pods get restarted because of liveness probe timeouts, pods are unable to communicate with other services, e.g. service -> vault to rotate / renew the database credentials.

See my `values.yml` and consul server logs below. I'm happy to provide more information.

### Reproduction Steps

Steps to reproduce this issue, eg:

1. When running helm install with the following [values.yml](https://github.com/hashicorp/consul-k8s/files/11614109/values.yml.txt):

1. let it run for some time

1. services start failing randomly

### Logs

[consul-server-0.log](https://github.com/hashicorp/consul-k8s/files/11614077/0.log)
[consul-server-1.log](https://github.com/hashicorp/consul-k8s/files/11614083/1.log)
[consul-server-2.log](https://github.com/hashicorp/consul-k8s/files/11614085/2.log)

### Expected behavior

Services keep their connectivity.

### Environment details

- `consul-k8s` version: 1.0.7
- `values.yaml` used to deploy the helm chart: see above
- Kubernetes version: v1.24.13-eks-0a21954
- Cloud Provider: EKS
- Networking CNI plugin in use: aws vpc cni

**Comment by david-yu** [comment]
Out of curiosity does this persist in Consul K8s 1.0.9? I believe we merged this PR which may help: https://github.com/hashicorp/consul-k8s/pull/2520

**Comment by david-yu** [comment]
Will go ahead and close as no response was given to the previous query.
