### ISSUE TITLE
Consul connect environment variable injection fails when using different datacenter upstream

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#246]
If setting an upstream annotation like:
```
    "consul.hashicorp.com/connect-service-upstreams": "static-server:1234:dc2"
```
The environment variables `STATIC_SERVER_CONNECT_SERVICE_HOST=127.0.0.1`, `STATIC_SERVER_CONNECT_SERVICE_PORT=1234` aren't injected.

This is due to the logic here: https://github.com/hashicorp/consul-k8s/blob/master/connect-inject/container_env.go#L18-L20 which doesn't account for the colon-separated datacenter.

**Comment by ishustava** [comment]
Fixed by #250
