### ISSUE TITLE
BUG+FIX: Endpoints controller fails to deregister services

### ISSUE THREAD

**Issue by mr-miles** [hashicorp/consul-k8s#2491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We regularly see orphan services "stuck" in the catalog - the services are terminated as expected by k8s but this does not always reflect in the consul service catalog - leaving the last state of the service "frozen".  The impact is catastrophic in the service mesh because if the service is healthy it will continue to be part of envoy clusters and therefore yield intermittent errors to callers.  Worse, if the service is a terminating gateway then those errors will apply to any outbound connection in any service.

We have identified the root cause of this problem as a timing issue in the connect-inject endpoint controller.

The issue occurs in any environment where nodes are dynamically provisioned, for example with EKS+karpenter, or using spot instances.

The issue is mentioned in many issue reports - #2085 #2065 #1817 #1935 #15908 https://github.com/hashicorp/consul/issues/15908 

### Root cause

The controller is triggered by a change event to the endpoint object.
When the controller receives the event, it carries out deregistration with this code:
https://github.com/hashicorp/consul-k8s/blob/920ee3233d41792134a02f7a0e9e1d2d5ed4482d/control-plane/connect-inject/controllers/endpoints/endpoints_controller.go#L1095C44-L1095C44
This is calling the k8s api to retrieve a list of active k8s nodes, and then goes on to find service instances on each of those nodes to true up.

The issue is that if there is any delay in processing the event, the list of nodes that is retrieved may not be the same as when the event was generated.  If a service is registered to a synthetic node in the consul catalog that is not in the node list that the controller retrieves, then it will not be deregistered.

An example scenario:

- A cluster with 5 nodes.  One node running 10 pods is shut down
- K8s generates the endpoint events as expected as pods are terminated
- The controller processes the first 7 events.  The controller retrieves a node list containing all 5 nodes.
- The node is now empty and k8s removes it.
- The controller processes the remaining 3 events.  The controller retrieves a node list containing just 4 nodes.  The service instances registered to the now-dead 5th node are not deregistered and are left as orphans.

### Reproduction Steps

Because there is timing involved, it is hard to reproduce with 100% regularity.
We have most success reproducing this by deleting nodes that are running many pods so that k8s attempts to reschedule them elsewhere  - since the events are processed in order, the last events have the greatest timing difference.

A code-related way to exacerbate the issue is to introduce a delay in the controller.

### Fix

#2258 contains a code change which we have been testing and eliminates the issue in our environment.
The fix retrieves the node list from consul rather than k8s, and compares it to the endpoint list - thereby removing the possibility that they are out-of-sync.

During the course of testing I also noticed that the synthetic nodes are never deregistered from the consul catalog.  Querying the API shows that we currently have 200+ synthetic nodes in the catalog compared to 6 live nodes in the k8s cluster.

**Comment by david-yu** [comment]
@mr-miles Just to double check you are indeed using Consul K8s 1.0.x or above with Consul 1.14 or above correct? We took a quick glance at the PR but will need to look at this more thoroughly to test that it does fix the problem.

**Comment by mr-miles** [comment]
Yes, I can confirm we are on vLatest of the chart and the container image.

Hopefully you’re able to reproduce the issue - but more than happy to chat
if more input is useful.

**Comment by david-yu** [comment]
Closing as the PR is now merged: https://github.com/hashicorp/consul-k8s/pull/2571. This should be released in 1.2.x, 1.1.x, and 1.0.x by mid August timeframe for our next set of patch releases.

**Comment by sayap** [comment]
@mr-miles Thanks for the fix! I am a fellow user of consul-k8s, and still have a lingering concern about agentless even after the bug fix.

If I understand correctly from https://github.com/kubernetes/kubernetes/issues/55713#issuecomment-538625309, if a node wasn't shutdown gracefully, then pods that were running on it will stay as `Status: Running` for about 5 minutes, before getting rescheduled to another node. With agentless, it means the service mesh will still be directing traffic to these unreachable pods for about 5 minutes?

Currently, we are still on consul-k8s < 1.0 with consul agents running as a daemonset. While this has all the downsides mentioned in https://www.youtube.com/watch?v=-ij_q-sdsoM, the failure detection capability of gossip seems to be superior than what's provided by kubernetes.

**Comment by sayap** [comment]
Just realized that there are a few options that can mitigate the impact:
* https://karpenter.sh/preview/concepts/deprovisioning/#termination-controller
* https://github.com/aws/aws-node-termination-handler
* https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown

In the case of a sudden hardware failure, gossip is still the best choice, but such an event shouldn't happen too frequently.
