### ISSUE TITLE
Consul Inject Sidecar

### ISSUE THREAD

**Issue by antonyaugustus** [hashicorp/consul-k8s#258]
Hi,

I'm trying to find a way to enabled resources for consul connect Inject sidecars on namespaces that have resource quotas enabled. I went through PR#200.

Also I tried using proxyDefaults as below in the helm values but could not get to inject the values into the sidecars. Any help/pointer?

connectInject:
  enabled: true
  default: false
  overrideAuthMethodName: consul-auth
  proxyDefaults: |
    {
      "resources" : {
        "limits" : {
          memory" : "128Mi"
        },
        "requests" : {
          memory" : "128Mi"
        }
      }
    }

**Comment by lkysow** [comment]
This was answered here: https://discuss.hashicorp.com/t/consul-inject-sidecar-with-resources/8422/2?u=lkysow
