### ISSUE TITLE
Provide openapi schema for all custom CRDs

### ISSUE THREAD

**Issue by komapa** [hashicorp/consul-k8s#2721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Feature Description

We would love to have openapi schema for the custom CRDs so we can use it with `kustomize` as described here: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/customOpenAPIschema.md

#### Use Case(s)

Deploying with `kubectl -k` or `kustomize build`

**Comment by missylbytes** [comment]
Hi @komapa, we do/should be generating OpenAPI schemas on our CRDs. https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/crd-gateways.yaml#L50
Is that what you are looking for? Or have you found a CRD that is missing it?

**Comment by komapa** [comment]
Okay, thank you. In that case I should be using ` kustomize openapi fetch` from the running cluster and get the OpenAPI spec that way?

Appreciate it!
