### ISSUE TITLE
Create policy and token for Ingress and Terminating gateways in the provided namespace rather than the default namespace

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#279]
Currently, when you provide a gateway flag with a namespace, e.g. `-terminating-gateway-name=terminating-gateway.tgw-namespace`, we only use that namespace for policy rules and ignore it when creating a token and a policy. This results in both the policy and the token to be created in the default Consul namespace.

This is not ideal, because then in order for the gateway to access its own policy or token, you need to attach the cross-namespace policy to the namespace where you're running the gateway. We should instead create them in the same namespace where the gateway is running.

**Comment by lkysow** [comment]
Note that for ingress this will mean that an ingress gateway in one namespace can only route to other services in that same namespace. Should be fine because if you need that functionality then you can deploy into the default ns but worth noting in docs after this is implemented.

**Comment by ishustava** [comment]
Closing because I wasn't able to reproduce. I believe the errors I saw were because I attached a policy to the terminating gateway token for a service that lived in a different namespace. In this case, an error is expected.
