### ISSUE TITLE
Whitelist Methodology.

### ISSUE THREAD

**Issue by lindenle** [hashicorp/consul-k8s#28]
We would like to NOT sync services by default but only add them using the annotation:

`consul.hashicorp.com/service-sync`

It appears from the docs (https://www.consul.io/docs/platform/k8s/service-sync.html):

`This default can be changed as configuration to the sync process.` 

That this should be possible. However I cannot figure out what setting to change in the helm chart.

What is the correct setting to pass in?

**Comment by adilyse** [comment]
The flag for setting this is supported (see the code [here](https://github.com/hashicorp/consul-k8s/blob/master/subcommand/sync-catalog/command.go#L52-L55)), but it seems to be missing from the Helm chart. I'm working on piping it through so it's easily set, as well as updating the docs to include the relevant information.

**Comment by adilyse** [comment]
Here's the link to the updated documentation: https://www.consul.io/docs/platform/k8s/helm.html#v-synccatalog-default. Hope that helps!
