### ISSUE TITLE
Cannot list services at the cluster scope

### ISSUE THREAD

**Issue by harlequin** [hashicorp/consul-k8s#286]
I'm receiving always the error message

`User "system:serviceaccount:ocp010041:consul-service-account" cannot list services at the cluster scope: no RBAC policy matched
`
I have only permissions on a seperate namespace.

Changing the service account ClusterRole to "cluster-admin" is not a possibility due to limited access.

How can I avoid that consul-k8s want's to scan the complete cluster?

**Comment by ishustava** [comment]
Hey @harlequin 

Thanks for creating an issue. Could you provide a bit more information? 

It'd be good to know which component you're referring to and where this error is coming from. Also, which version of consul-k8s are you using and how are you running it?

Without knowing the details, I'd say it'd depend on the component whether it's possible for it not to have cluster-level roles. For example, for the sync catalog, you can provide your namespace via the `-allow-k8s-namespace` flag of the `sync-catalog` command. Here is the description of this flag:

```
  -allow-k8s-namespace=<value>
     K8s namespaces to explicitly allow. May be specified multiple
     times.
```
So, if I'm working in the namespace called `iryna`, I can run catalog sync with `-allow-k8s-namespace=iryna`, and that should direct it only sync services within the `iryna` namespace.

Note that there is also a `-deny-k8s-namespace` flag which does the opposite:

```
  -deny-k8s-namespace=<value>
     K8s namespaces to explicitly deny. Takes precedence over allow. May
     be specified multiple times.
```

**Comment by harlequin** [comment]
sorry for the little details on start ;)

so i'm working with the docker container 0.16.0 and want to use the sync from k8s to consul.

My command line is

```
consul-k8s sync-catalog 
            -datacenter=eu-central-1 
            -k8s-source-namespace=ocp010041  
            -allow-k8s-namespace=ocp010041           
            -sync-clusterip-services=false 
            -node-port-sync-type=ExternalOnly 
            -to-k8s=false 
            -to-consul=true 
            -sync-lb-services-endpoints=true 
            -k8s-default-sync=false 
            -consul-service-prefix=k8s
```

**Comment by lkysow** [comment]
Hi, are you using the helm chart or installing things manually? The helm chart should be setting up the correct RBAC permissions. This is the clusterrole we create: https://github.com/hashicorp/consul-helm/blob/master/templates/sync-catalog-clusterrole.yaml

**Comment by lkysow** [comment]
Hi, we're going to close this issue because we haven't heard back. If you would like us to re-open please comment and we can do so.
