### ISSUE TITLE
Support telemetry.disable_hostname in Consul

### ISSUE THREAD

**Issue by DanielYWoo** [hashicorp/consul-k8s#2879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

We want the parameters supported in the Helm charts.
- https://developer.hashicorp.com/consul/docs/agent/config/config-files#telemetry-disable_hostname
- https://developer.hashicorp.com/consul/docs/agent/config/config-files#telemetry-enable_host_metrics

#### Feature Description

I cannot find it in the example values file so I assume this is not supported yet.

#### Use Case(s)

Better metrics processing.

#### Contributions

No

**Comment by david-yu** [comment]
Hi @DanielYWoo you should be able to apply the config via `server.extraConfig`: https://developer.hashicorp.com/consul/docs/k8s/helm#v-server-extraconfig like so 

```
telemetry {
  disable_hostname: true
  enable_host_metrics: true
}
```

**Comment by DanielYWoo** [comment]
Oh, that should work. I will close this PR. Thanks!
