### ISSUE TITLE
Publish consul-k8s-control-plane Docker image to ECR

### ISSUE THREAD

**Issue by ilpianista** [hashicorp/consul-k8s#3091]
#### Is your feature request related to a problem? Please describe.

consul-k8s-control-plane Docker images are missing on ECR while several hashicorp images are available (even vault or the vault-csi-provider). Please consider to upload images to ECR.

#### Feature Description

Mirror consul-k8s-control-plane Docker images.

**Comment by david-yu** [comment]
@ilpianista Although we have the same images on Hub and you should be able to pull them on EKS, is this reason for the request more related to increased cost due to pulling from non-ECR repos?

**Comment by ilpianista** [comment]
@david-yu yes
