### ISSUE TITLE
Add polling mode to `get-consul-client-ca` command

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/consul-k8s#310]
The help text alludes to a "continuous polling" operation mode and the source code has an unused [`flagPollingInterval`](https://github.com/hashicorp/consul-k8s/blob/53aca864e185c088fecc71d4eb29945ea7d90290/subcommand/get-consul-client-ca/command.go#L34) flag.

**Comment by lkysow** [comment]
This command already polls but its interval is hardcoded to 1s. If there are issues with that interval let us know and I can re-open.
