### ISSUE TITLE
Is consul client backward compatible with v1.0.0 ?

### ISSUE THREAD

**Issue by MageshSrinivasulu** [hashicorp/consul-k8s#3211]
As per the documentation, the consul clients are not enabled by default from v1.0.0. 

If we enable it, will the consul client be backwards compatible? Can the pods still use the client to communicate with the consul server?

I am looking at a scenario where existing pods are still using the envoy proxy sidecar during the upgrade and my understanding is consul dataplane sidecar will only be injected if the old pods are being restarted.

So once we make the upgrade do the existing pods fail to communicate with the consul server? or else it will work as usual if we the consul client enabled

![image](https://github.com/hashicorp/consul-k8s/assets/79187874/e91e6317-faa7-4c0a-9b79-bfc68d18b851)

**Comment by david-yu** [comment]
Consul clients are no longer deployed as part of Consul Service mesh when upgrading to 1.0.0.PLease read more about this here: https://developer.hashicorp.com/consul/docs/connect/dataplane. We no longer support gossip communication on the dataplane for service mesh on Kubernetes as it cause lots of deployment challenges for users and customers in the past. Let me know if that helps!

**Comment by blake** [comment]
@MageshSrinivasulu, Consul clients will still be able to communicate with the servers when they are upgraded to 1.14 or later.

> I am looking at a scenario where existing pods are still using the envoy proxy sidecar during the upgrade and my understanding is consul dataplane sidecar will only be injected if the old pods are being restarted.

This is correct.

> once we make the upgrade do the existing pods fail to communicate with the consul server? or else it will work as usual if we the consul client enabled

The existing pods will continue to work if the Consul clients are enabled.

See <https://developer.hashicorp.com/consul/docs/k8s/upgrade#upgrading-to-consul-dataplane> for details on how to safely upgrade your environment to the dataplane architecture.

**Comment by david-yu** [comment]
Will close since I believe you have answered your question. Let us know if that is not the case!
