### ISSUE TITLE
mTLS for `kube-system` resources 

### ISSUE THREAD

**Issue by aliasboink** [hashicorp/consul-k8s#3223]
Disclaimer: I am new to both Kubernetes and Consul.

### Context 
The cluster is deployed in Oracle Cloud Infrastructure.

### Question
**Question Context:** To my understanding when you deploy applications, the Envoy sidecar proxy will be deployed alongside the pods of the applications and all communication will be done via said proxies. Service Intentions ought to be created to know which way the data can flow from pod to pod (I am aware different configurations can be made with permissive mTLS and the like).

In the previously described scenario, how are the `kube-system` pods handled? Are the `CoreDNS`, `kube-flannel`, `kube-proxy`, etc. a special case in the sense that they're handled differently that your typical namespaces? 
Any clarification on this or/and documentation would be greatly appreciated!

Thank you!

**Comment by blake** [comment]
Hi @aliasboink,

The `kube-system` and `local-storage-path` namespaces are exempt from sidecar injection. 

You can optionally exempt additional namespaces from traffic redirection using the [`connectInject.namespaceSelector`](https://developer.hashicorp.com/consul/docs/k8s/helm#v-connectinject-namespaceselector) option in the Helm chart configuration.

See <https://developer.hashicorp.com/consul/docs/k8s/installation/install#enable-consul-service-mesh-on-select-namespaces> for more info.

**Comment by aliasboink** [comment]
Hello, thank you a lot!
I've closed this issue as the question has been answered.
