### ISSUE TITLE
[SECURITY] sidecar security context config

### ISSUE THREAD

**Issue by isaaccarrington** [hashicorp/consul-k8s#347]
Containers in my Kubenernetes environment must not run as root and need `runAsUser` set for the security context. 
e.g
`      securityContext:
          runAsUser: 1000`

Is this possible? Can it be made possible?

**Comment by lkysow** [comment]
Hi, is this specifically for the injected sidecars when using service mesh?

**Comment by isaaccarrington** [comment]
Hey @lkysow, yeah that is exactly it

**Comment by isaaccarrington** [comment]
I am running Consul 1.8.4 and the error message in the application pods is
`  Normal   Pulled     23s (x3 over 25s)  kubelet, nzakdot6168rzrw.elinux.westpac.co.nz  Successfully pulled image "docker.artifactory2.westpac.co.nz/consul:1.8.4"
  Warning  Failed     23s (x3 over 25s)  kubelet, nzakdot6168rzrw.elinux.westpac.co.nz  Error: container has runAsNonRoot and image will run as root`

**Comment by isaaccarrington** [comment]
I have Consul version 1.8.4. The error message is
`  Normal   Pulled     23s (x3 over 25s)  kubelet, #######.co.nz  Successfully pulled image "docker.artifactory2.#######.co.nz/consul:1.8.4"
  Warning  Failed     23s (x3 over 25s)  kubelet, #########.co.nz  Error: container has runAsNonRoot and image will run as root`

**Comment by isaaccarrington** [comment]
I've updated the container securitycontexts and actually got this working. I'll rework it so that it is configurable via helm and has a default, then submit a PR

**Comment by isaaccarrington** [comment]
Sorry I havn't forgotten. Hopefully get around to the PR this side of Christmas

**Comment by david-yu** [comment]
Closing as this is addressed via https://github.com/hashicorp/consul-k8s/pull/493
