### ISSUE TITLE
catalog-sync k8s->consul: Is there a way to disable LoadBalancer type services syncing?

### ISSUE THREAD

**Issue by laithalissa** [hashicorp/consul-k8s#386]
From reading the docs I can only see a way to disable ClusterIP services being synced to consul, but no setting for LoadBalancer type services. I had a quick spelunk into the code and didn't see a mechanic to disable it there either.

The only thing I can think of is to use explicit annotations to control what to sync.

Could you please advise if there's an easier way to disable LoadBalancer service sync?

**Comment by kschoche** [comment]
Hi there!
Thank you for submitting this question. Unfortunately as of right now the only way to disable synchronization of a loadbalancer service would be to - as you suggested - explicitly disable it via annotations.

You would do that by adding the annotation `"consul.hashicorp.com/service-sync" : false`

**Comment by laithalissa** [comment]
Thank you :)
