### ISSUE TITLE
API-Gateway pods is Init state and only changes to running state once we delete the service api-gateway.

### ISSUE THREAD

**Issue by tejnar** [hashicorp/consul-k8s#3890]
#### Question
1. API-Gateway pods is Init state and only changes to running state only once we delete the svc api-gateway. 

### Helm Configuration

Attached values.yaml file which is being used for deploying consul to EKS.
[values.yaml.txt](https://github.com/hashicorp/consul-k8s/files/14908416/values.yaml.txt)
Chart Details: 
version: 1.4.1
appVersion: 1.18.1
### Logs

[api-gw]$ kubectl -n mesh-client get all
NAME                                                      READY   STATUS                  RESTARTS        AGE
pod/api-gateway-68bcd79b4d-p62bm                          0/1     Init:CrashLoopBackOff   5 (2m24s ago)   17m
pod/consul-consul-connect-injector-8cf9849c4-ksxd9        1/1     Running                 0               30h
pod/consul-consul-connect-injector-8cf9849c4-nm6zq        1/1     Running                 0               3d9h
pod/consul-consul-server-0                                1/1     Running                 0               3d9h
pod/consul-consul-server-1                                1/1     Running                 0               37h
pod/consul-consul-server-2                                1/1     Running                 0               3d14h
pod/consul-consul-webhook-cert-manager-5dc74f9bbb-ltssk   1/1     Running                 0               30h

NAME                                     TYPE           CLUSTER-IP      EXTERNAL-IP                                                                     PORT(S)                                                                            AGE
service/api-gateway                      LoadBalancer   172.20.137.66   api-gateway.elb.us-east-1.amazonaws.com   80:32370/TCP                                                                       111m
service/consul-consul-connect-injector   ClusterIP      172.20.22.178   <none>                                                                          443/TCP                                                                            3d14h
service/consul-consul-server             ClusterIP      None            <none>                                                                          8500/TCP,8502/TCP,8301/TCP,8301/UDP,8302/TCP,8302/UDP,8300/TCP,8600/TCP,8600/UDP   3d14h
service/consul-consul-ui                 NodePort       172.20.63.191   <none>                                                                          80:30904/TCP                                                                       3d14h

NAME                                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/api-gateway                          0/1     1            0           3d
deployment.apps/consul-consul-connect-injector       2/2     2            2           3d14h
deployment.apps/consul-consul-webhook-cert-manager   1/1     1            1           3d14h

NAME                                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/api-gateway-68bcd79b4d                          1         1         0       3d
replicaset.apps/consul-consul-connect-injector-8cf9849c4        2         2         2       3d14h
replicaset.apps/consul-consul-webhook-cert-manager-5dc74f9bbb   1         1         1       3d14h

NAME                                    READY   AGE
statefulset.apps/consul-consul-server   3/3     3d14h
### Current understanding and Expected behavior

We use spot instances in our cluster and api-gateway pod can be migrated to any other node in the cluster. 
My expectation is it should bring the api-gateway pod to running state, since there is an associated service(api-gateway) which is already running. I've also defined httproute as defined in documentation(https://developer.hashicorp.com/consul/tutorials/kubernetes/kubernetes-api-gateway#deploy-api-gateway).

Once I delete the service(api-gateway), it brings the pod to running state and it was working as expected. Also able to get the response from the services deployed inside the eks cluster.

### Environment details
EKS version : 1.29  with Calico-cni enabled

### Additional Context
Modify the connect-inject-deployment.yaml to use hostNetwork:true

**Comment by andriktr** [comment]
Have the same issue since version `consul-dataplane:1.4.1` `consul-k8s-control-plane:1.4.1` for me removing the ACL roles associated to API GW fixes the issue, but it's temporary.

**Comment by andriktr** [comment]
Same issue is in consul 1.17.4. Also noticed the following errors in consul-connect-injector
```
consul-experimental-connect-injector-867cb947cc-r9stj:sidecar-injector 2024-04-22T06:32:36.284Z ERROR   Reconciler error        {"controller": "gateway", "controllerGroup": "gateway.networking.k8s.io", "controllerKind": "Gateway", "Gateway": {"name":"consul-experimental-api-gateway","namespace":"consul"}, "namespace": "consul", "name": "consul-experimental-api-gateway", "reconcileID": "0100eea3-d83e-49b5-9cee-dfe4d7b7ef15", "error": "Unexpected response code: 500 (Invalid Role: A Role with Name \"managed-gateway-acl-role-consul-experimental-api-gateway\" already exists)"}
```
Maybe it related to this bugfix in the latest releases:
<img width="797" alt="image" src="https://github.com/hashicorp/consul-k8s/assets/25537180/bdfc6adb-ad80-495e-826e-130478e92018">

**Comment by tejnar** [comment]
Thanks for checking. I don't see this issue when exposing it using a NodePort. This issues occurs only when the servicetype: loadbalancer. As you said it might be bug.

**Comment by tejnar** [comment]
I've created as bug(https://github.com/hashicorp/consul-k8s/issues/3934) for the same and will close this one.
