### ISSUE TITLE
K8s Health checks for services registered on Consul

### ISSUE THREAD

**Issue by phr0zenx** [hashicorp/consul-k8s#394]
Is there a way I can implement health checks via k8s to check on the services registered through consul? 

I want to implement pod regenerative triggers that k8s is able to execute. Unless consul is able to do that?

**Comment by kschoche** [comment]
Hi @phr0zenx , thank you for submitting this issue.
I'm not totally clear on what your question is on this one, could you elaborate a bit more on what you're trying to do?

Right now there is support for k8s->consul health probe synchronization which uses k8s probes to influence how Consul directs service mesh traffic, so as to avoid a situation where an unhealthy pod is receiving mesh requests.
You could pair that with a liveness probe in k8s but the flow of information in the current design is from k8s to Consul and not the other way around with health checks.

Can you describe in a bit more detail what your goal is and also some idea of how you'd see it designed?

Thanks!

**Comment by lkysow** [comment]
Hi @phr0zenx, since we haven't heard back we're going to close this but if you re-comment then we're happy to reopen.
