### ISSUE TITLE
Support for an ingress-gateway CRD

### ISSUE THREAD

**Issue by arctiqjacob** [hashicorp/consul-k8s#402]
It would be great to allow users to define an Ingress Gateway configuration entry natively in Kubernetes through a CRD. Currently the way to do this is as shown [here](https://www.consul.io/docs/k8s/connect/ingress-gateways#submitting-an-ingress-gateway-configuration-entry).

For Kubernetes users who are used to writing YAML files and interacting with the Kubernetes API, switching to this type of config entry and interacting with Consul directly can be discouraging to some.

My thinking is that this would be implemented similarly as the native Kubernetes Ingress object or Istio’s Virtual Service where users can define the Consul service and port that the service is listening on.

**Comment by david-yu** [comment]
Hi @arctiqjacob we do anticipate working on this in the future. We may take a more phased approach by first building the support to configure both Terminating and Ingress gateways first, and in the future also support installing them rather than through Helm. Would that work for you?

**Comment by lawliet89** [comment]
@david-yu It would be great if CRDs can both install and configure Terminating/Ingress GWs. It would make it easier to decouple the management of these gateways from the Helm Chart.

**Comment by blake** [comment]
@lawliet89 Version 0.28.0 of the Helm chart was just released which adds support for ingress and terminating gateway CRDs. https://github.com/hashicorp/consul-helm/releases/tag/v0.28.0

**Comment by lawliet89** [comment]
Thanks @blake -- just to double check, does the CRD just create the Config Entry or does it also spawn new Gateways themselves?
