### ISSUE TITLE
consul-k8s disconnected syncer scenario

### ISSUE THREAD

**Issue by bondido** [hashicorp/consul-k8s#404]
Hi,
We have consul-k8s running on k8s (as single pod deployment, not a helm chart) in the cloud syncing annotated k8s services to consul DC on-premise.

k8s services are registered in consul catalog as external services "running" on k8s-sync node.

We can dynamically "discover" k8s services from on-premise, not containerized apps. Nice, easy and working great. 

But, as being external services, k8s services are not healthchecked in any way by consul. We rely only on syncer registering their "coordinates" to consul or not.

Even having no doubt that they are registered right, lets consider scenario in which syncer is lost some way (syncer itself killed, k8s cluster failed, or cloud<->on-premise network issues.

In such cases we are left with k8s services registered as discoverable in our consul catalog while they should be unregistered or change state to critical.

How should we handle that?

**Comment by lkysow** [comment]
Hi bondido,
What are the service types you're syncing? e.g. `ClusterIP`, `LoadBalancer`, etc.

**Comment by bondido** [comment]
`ClusterIP` and `LoadBalancer`, exactly these two.

**Comment by bondido** [comment]
> Hi bondido,
> What are the service types you're syncing? e.g. `ClusterIP`, `LoadBalancer`, etc.

ClusterIP and LoadBalancer, exactly these two.

**Comment by lkysow** [comment]
If the syncer comes back up, it will deregister any services that aren't supposed to be there.

If the syncer is never restarted, then you'll have to make API calls to Consul to delete those services.

**Comment by bondido** [comment]
Thanks for answer @lkysow 
Would it be possible for syncer, maybe in future versions, to work with consul-esm (External Service Monitor)?
In our scenario where we have on-premise consul DC and cloud provider hosted kubernetes syncing services, could the services be registered in consul with health checks (defined for example by k8s service annotation) and those health checks "consumed" and executed by consul-esm running on-premise?
In case of syncer/kubernetes cluster problems or even deleted (accidentaly or not), consul-esm could 'fail' synced services causing external applications stop discovering them. Now there can be some gap (causing problems) between syncer disapear and us calling consul API deregistering "de facto failing" services.

**Comment by lkysow** [comment]
That does sound like an interesting idea. Would you mind creating a feature request to track?

**Comment by david-yu** [comment]
Closing since the use case is related to consul-ism which is tracked here: https://github.com/hashicorp/consul-k8s/issues/411
