### ISSUE TITLE
Multi-Cluster Deploy

### ISSUE THREAD

**Issue by Ginja** [hashicorp/consul-k8s#42]
This may be a duplicate of #6, if so please feel free to close this, but currently running more than one consul-k8s deployment across different clusters results in the deployments fighting one another:

```
2018-12-07T05:39:41.560Z [INFO ] to-consul/sink: invalid service found, scheduling for delete: service-name=SERVICE_NAME
```

I'd ideally like to be able to run multiple deployments across clusters, and have a particular deployment only manage what it synced. Would adding a `-svc-tag` option solve this I wonder? I'm thinking if set consul-k8s would only manage the services, and more specifically the nodes, with said tag value? Something like this would solve our use case as we do have multiple clusters with the same service defined in both.

**Comment by Ginja** [comment]
Looks like this would be resolved with #39

**Comment by adilyse** [comment]
Merged a configurable tag that should allow each Kubernetes cluster's services to be independently identified, which should solve this conflict. It will be included in the next released version, which should happen soon.

Please feel free to reopen if this doesn't fix your issue.

**Comment by jacksontj** [comment]
@adilyse is there an ETA for a release that would include this fix?
