### ISSUE TITLE
-ca-file and -http-addr don't take effect

### ISSUE THREAD

**Issue by whiskeysierra** [hashicorp/consul-k8s#436]
When filing a bug, please include the following headings if possible. Any example text in this template can be deleted.

### Overview of the Issue

```
$ consul-k8s inject-connect -h

  -ca-file=<value>
     Path to a CA file to use for TLS when communicating with Consul.
     This can also be specified via the CONSUL_CACERT environment
     variable.

  ...

  -http-addr=<address>
     The `address` and port of the Consul HTTP agent. The value can be
     an IP address or DNS address, but it must also include the port.
     This can also be specified via the CONSUL_HTTP_ADDR environment
     variable. The default value is http://127.0.0.1:8500. The scheme
     can also be set to HTTPS by setting the environment variable
     CONSUL_HTTP_SSL=true.
```

I tried to specify both, the `-ca-file` and `-http-addr` option, but they wouldn't be used, as far as I can tell.
Using the corresponding env vars, `CONSUL_CACERT` and `CONSUL_HTTP_ADDR` worked.

### Reproduction Steps

Try to use the CLI options.

### Logs

Include any relevant logs.

<details>
  <summary>consul-k8s logs</summary>

```
CONSUL_HTTP_ADDR is not specified
2021/02/05 15:44:16 http: TLS handshake error from 10.200.0.4:46174: No certificate available.
```

</details>

### Expected behavior

Since both options are documented in the help, I'd expect them to work.

### Environment details

If not already included, please provide the following:
- `consul-k8s` version: hashicorp/consul-k8s:0.23.0
- `consul-helm` version: n/a
- `values.yaml` used to deploy the helm chart: n/a

Any other information you can provide about the environment/deployment.

### Additional Context

Additional context on the problem.

**Comment by david-yu** [comment]
Hi @whiskeysierra thanks for filing it looks like those flags don't set via the consul-k8s cli. Could you tell us more about how you are utilizing the Consul k8s binary? We have typically not recommended using the binary standalone without the Helm chart. We didn't catch this before because the Helm chart utilizes those environment variables as you described.

**Comment by lkysow** [comment]
I think these are being parsed. If I compile locally and comment out lines these lines:

```go
	// We must have an in-cluster K8S client
	//if c.clientset == nil {
	//	config, err := rest.InClusterConfig()
	//	if err != nil {
	//		c.UI.Error(fmt.Sprintf("Error loading in-cluster K8S config: %s", err))
	//		return 1
	//	}
	//	c.clientset, err = kubernetes.NewForConfig(config)
	//	if err != nil {
	//		c.UI.Error(fmt.Sprintf("Error creating K8S client: %s", err))
	//		return 1
	//	}
	//}

```

And the set `-ca-file` to a non existent file I get this error:

```
consul-k8s inject-connect -consul-k8s-image=img -consul-image=img -envoy-image=img -ca-file=/file/does/not/exist
Error reading Consul's CA cert file "/file/does/not/exist": open /file/does/not/exist: no such file or directory
```

>  but they wouldn't be used, as far as I can tell.

Can you describe the symptoms as to what isn't working?

**Comment by whiskeysierra** [comment]
I used the helm chart as a start but compiled it to manifest files and customized them a bit. I tried to make it a bit shorter and tried the command line options, when possible. The primary reason for customisation was the desire to not having to distribute tokens via secrets. I did that using kubernetes auth method, service accounts, binding rules and init containers that use `consul login`.

**Comment by whiskeysierra** [comment]
Regarding symptoms, please see the logs in my original post. The output was printed respectively when using the command line options and switching to env bars fixed it.

**Comment by lkysow** [comment]
Oops, sorry I missed that. `-ca-file` is passed but `-http-addr` is not passed to all components. This will be fixed by #432.

**Comment by lkysow** [comment]
>  The primary reason for customisation was the desire to not having to distribute tokens via secrets. I did that using kubernetes auth method, service accounts, binding rules and init containers that use consul login.

This is a direction we'd like to go actually. The reason secrets are used right now is simply because the first version of the chart was created before auth methods existed. Is it working? Any tips for when we go down that road?

**Comment by whiskeysierra** [comment]
> Is it working?

Yes, works.

> Any tips for when we go down that road?

Plenty. Before I write them down here, should we move this discussion over to https://github.com/hashicorp/consul-helm?

**Comment by lkysow** [comment]
Sounds good. I opened https://github.com/hashicorp/consul-helm/issues/811 to track and you can add your comments there. I'll close this issue since #432 will fix.
