### ISSUE TITLE
sync-catalog: K8s to Consul: Support Ingress objects

### ISSUE THREAD

**Issue by muffin87** [hashicorp/consul-k8s#5]
Hi everyone,

I was wonderring if it's also possible to support syncing Ingress objects.
I believe that the use of Ingress controllers is quite common to expose http(s) based services to the outside of the cluster. They offer quite big feature set which makes it easy to manage certain settings like TLS cert handling or path / name based routing. Without the Ingress controller I would need to reinvent these features for every service.

The tricky part for this feature is how to transform the Ingress object into DNS. One solution could be to create a CNAME for each object and let it point to the A record of the Ingress controller IP. The Ingress controller service needs to be from type `LoadBalancer` of course.

An example would be:

Ingress controller service:

```
NAME                    TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE     SELECTOR
traefik                 LoadBalancer   10.253.35.66     28.125.10.5   80:32281/TCP,443:32209/TCP   1d      app=traefik,component=proxy
```

This would create a A record like this:

```
traefik.example.com. 3600 IN     A       28.125.10.5
```

Now I got a webservice which I want to expose. I would create an Ingress object and set the `host` field like `awesomeservice.example.com`. This would create the following DNS entry:

```
awesomeservice.example.com. 3600 IN     CNAME   traefik.example.com.
traefik.example.com.        3600 IN     A       28.125.10.5
```

**Comment by splashx** [comment]
Maybe @adilyse could help with the design on this? I could take a shot on the implementation but it would be good if we have an expectation if this is even desirable/possible without major refactoring..

**Comment by splashx** [comment]
@muffin87 did you ever solve this problem? I was looking into https://github.com/aswinkarthik/ingress-consul-register but it doesnt look very complete..

**Comment by joshbenner** [comment]
I released something we've been using successfully in production: https://pypi.org/project/consulk8s/, and we recently refactored this into a metacontroller-compatible operator we run in the cluster.

**Comment by yarinm** [comment]
+1 for this, service sync should support ingresses as well.

The suggested alternatives are far from ideal and I might have to resort to using one of them.

**Comment by owenJiao** [comment]
Now I use ingress to expose service in k8s, meanwhile, I use consul as our service discovery tool, so I wonder if this feature can work now?

**Comment by david-yu** [comment]
Hi @owenJiao we don't support syncing Ingress objects via catalogSync. We are willing to take PRs though for this work if you are interested in contributing.
