### ISSUE TITLE
Problem with IPs joining existing cluster

### ISSUE THREAD

**Issue by tushar00jain** [hashicorp/consul-k8s#50]
It's mentioned in the following link that joining an existing cluster is possible https://www.consul.io/docs/platform/k8s/run.html.

I'm in a similar situation where I have an existing consul cluster running outside the kubernetes cluster and I want to have just the consul agent inside the kubernetes cluster. However, the problem is with the IP addresses. In order for the nodes outside the cluster to access the pods inside kubernetes, I have set up a node port service and the advertised IP is set to the node's IP. The problem is that the pods inside the cluster see the incoming request as from the pod's IP not the node's IP, whereas the nodes outside kubernetes have no way to interact with kubernetes with the pod IP.

Of course running only 1 agent inside kubernetes works because this conflicting IP issue does not occur. Any solutions for this? Some possible solutions perhaps but I haven't tried

1. Configuring iptables such that the IP address is changed to use the node's IP address when accessing consul ports inside kubernetes. But this will require manually configuring kubernetes nodes.
2. Use AWS CNI so that the nodes can communicate directly with the pods using the pod's IP address but this could only work for AWS

Is there any other way that this issue can be resolved?

**Comment by tushar00jain** [comment]
I have also opened the issue here https://github.com/hashicorp/consul-helm/issues/96 but there doesn't seem to be much activity on that repository so feel free to close either one

**Comment by tushar00jain** [comment]
ok a simpler solution by using `hostNetwork` seems to be working fine

**Comment by buluxan** [comment]
hi @tushar00jain  ,

in which file hostnetwork will be put , because i'm going to using external consul cluster also 
agent will be running on HOST 

thx,

**Comment by tushar00jain** [comment]
@buluxan please check out the issue that I have referenced

**Comment by buluxan** [comment]
ok thx u @tushar00jain

**Comment by lkysow** [comment]
This will be tracked in https://github.com/hashicorp/consul-helm/issues/253 so I'm going to close this issue.
