### ISSUE TITLE
Unable to resolve internal k8s services from consul using k8s-sync 

### ISSUE THREAD

**Issue by shomeprasanjit** [hashicorp/consul-k8s#520]
We have currently configured consul catalog sync to auto-discover services within k8s cluster, we are using both-way sync using the official helm chart.  

```  
# toConsul and toK8S control whether syncing is enabled to Consul or K8S
# as a destination. If both of these are disabled, the sync will do nothing.
toConsul: true
toK8S: true
```
Ideally, we should be able to resolve internal k8s services which uses `k8s-sync` node by referring to `<catalog-service-name>.service.consul` from anywhere within the k8s cluster. but unfortunately, that is not the case.  

Is this a config issue or a bug?  I found a similar [issue](https://github.com/hashicorp/consul-k8s/issues/119) which is now closed. 

if I use `.` at the end of the catalog service endpoint, it points to the right pods.  

Below are the details: 

```
$ kubectl exec -it consul-consul-server-0 -n ABC -- consul catalog services -tags | grep druid-broker-hs-druid
druid-coordinator-hs-druid                       k8s
$
```

```
/ # dig +search druid-broker-hs-druid.service.consul

; <<>> DiG 9.12.4-P2 <<>> +search druid-broker-hs-druid.service.consul
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21088
;; flags: qr aa rd; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: ed599cdfcecf6f02 (echoed)
;; QUESTION SECTION:
;druid-broker-hs-druid.service.consul.cloudops.svc.cluster.local. IN A

;; ANSWER SECTION:
druid-broker-hs-druid.service.consul.cloudops.svc.cluster.local. 5 IN CNAME consul.service.consul.
consul.service.consul.	5	IN	A	10.150.13.161
consul.service.consul.	5	IN	A	10.150.12.184
consul.service.consul.	5	IN	A	10.150.11.35

;; Query time: 2 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; WHEN: Tue May 18 23:14:07 UTC 2021
;; MSG SIZE  rcvd: 313

/ #
```

whereas the below lookup works. 

```
/ # dig +search druid-broker-hs-druid.service.consul.

; <<>> DiG 9.12.4-P2 <<>> +search druid-broker-hs-druid.service.consul.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10230
;; flags: qr aa rd; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;druid-broker-hs-druid.service.consul. IN A

;; ANSWER SECTION:
druid-broker-hs-druid.service.consul. 5	IN A	10.150.11.226
druid-broker-hs-druid.service.consul. 5	IN A	10.150.12.142
druid-broker-hs-druid.service.consul. 5	IN A	10.150.12.11

;; Query time: 3 msec
;; SERVER: 172.20.0.10#53(172.20.0.10)
;; WHEN: Tue May 18 23:20:36 UTC 2021
;; MSG SIZE  rcvd: 221
```

Below is the `/etc/resolv.conf` file for `ABC` namespace. 
```
/ # cat /etc/resolv.conf
nameserver 172.20.0.10
search ABC.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
/ #
```

Below is my coredns config map data and has been configured as per [doc](https://github.com/hashicorp/consul-k8s/issues/119). 
```
Data
====
Corefile:
----

.:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf
    cache 30
    loop
    reload
    loadbalance
}
consul {
  errors
  cache 30
  forward . 172.20.9.34
}
```

`172.20.9.34` is the `consul-consul-dns` Service Cluster IP. 

### Expected behavior

It should be able to resolve using `<catalog-service-name>.service.consul`

### Environment details

- `consul-k8s` version: Consul v1.8.0

**Comment by shomeprasanjit** [comment]
Any updates ?

**Comment by ndhanushkodi** [comment]
Hey @shomeprasanjit do you have a use case for having both `toConsul: true` and `toK8S: true`? To use consul dns addresses like `<catalog-service-name>.service.consul` you should be able to set `toK8S: false`. That way, it won't sync the consul service to Kubernetes which is what is causing the DNS resolution issue in the issue you linked.

**Comment by shomeprasanjit** [comment]
Hello @ndhanushkodi : i only have a usecase to syn from k8s to consul. 

I will then turn this off `toK8S: false` and redeploy consul. 

Thanks for your help @ndhanushkodi

**Comment by david-yu** [comment]
Closing based on the most recent response. Thank you for confirming!
