### ISSUE TITLE
consul-connect-inject-init "did not find correct number of services: 0" error in consul-k8s version: 0.26.0-beta2

### ISSUE THREAD

**Issue by pbtrudel** [hashicorp/consul-k8s#522]
### Overview of the Issue

I am trying to use and test the new Transparent Proxy feature, since it will be very useful for our deployment scenario.
I am using a freshly deployed k8s cluster, a new consul-helm deployment and I try to deploy any other service with service mesh integration.
The consul-connect-inject-init container fails and crash loops, so the pod never completes the init phase.

### Reproduction Steps

``helm install consul hashicorp/consul --set connectInject.enabled=true --set connectInject.default=true --version 0.32.0-beta2``
Once consul is running, deploy any service. In my case a simple centos manifest, but I have tried others with the same behavior.

```
kubectl get pods --watch
NAME                                                              READY   STATUS     RESTARTS   AGE
centos                                                            0/2     Init:1/2   0          107s
consul-consul-52wr6                                               1/1     Running    0          2m57s
consul-consul-connect-injector-webhook-deployment-78bb4bd7g8ckf   1/1     Running    0          2m57s
consul-consul-connect-injector-webhook-deployment-78bb4bd7gwfqm   1/1     Running    0          2m57s
consul-consul-nd47q                                               1/1     Running    0          2m57s
consul-consul-server-0                                            1/1     Running    0          2m57s
consul-consul-server-1                                            1/1     Running    0          2m57s
consul-consul-server-2                                            1/1     Running    0          2m56s
consul-consul-v77vg                                               1/1     Running    0          2m57s
consul-consul-vmjn6                                               1/1     Running    0          2m57s
consul-consul-webhook-cert-manager-6dbb5987cb-2vkk5               1/1     Running    0          2m57s
centos                                                            0/2     Init:Error   0          2m7s
centos                                                            0/2     Init:1/2     1          2m8s
```

### Logs

<details>
  <summary>consul-k8s logs</summary>

```
2021-05-21T18:11:01.556Z [INFO]  Unable to find registered services; retrying
2021-05-21T18:11:02.557Z [INFO]  Unable to find registered services; retrying
2021-05-21T18:11:03.558Z [INFO]  Unable to find registered services; retrying
2021-05-21T18:11:04.559Z [INFO]  Unable to find registered services; retrying
2021-05-21T18:11:05.560Z [INFO]  Unable to find registered services; retrying
2021-05-21T18:11:05.561Z [ERROR] Timed out waiting for service registration: error="did not find correct number of services: 0"
```

</details>

### Expected behavior

consul-connect-inject-init should complete successfully and register the service in consul.

### Environment details

- `consul` version: 1.10.0-beta2
- `consul-k8s` version: 0.26.0-beta2
- `consul-helm` version: 0.32.0-beta2
- `values.yaml` used to deploy the helm chart: connectInject.enabled=true and connectInject.default=true

**Comment by ishustava** [comment]
Hey @pbtrudel 

Did you have a kubernetes service for your `centos` application? As of consul-k8s 0.26.0-beta1 and consul-helm 0.32.0-beta1, we now require that all connect services have a kubernetes service too. Please see our release notes: https://github.com/hashicorp/consul-helm/releases/tag/v0.32.0-beta1.

**Comment by pbtrudel** [comment]
Hi @ishustava 
Thanks for the quick reply. I did not correctly understand that all connect services need a service in this version. This changes things quite a bit, I will have to do further testing.
But deploying an app with a functional cluster IP service does seem to work.
When deploying an ingress controller like nginx or apache so that it can forward traffic to services within the service mesh doesn't seem to work. The app doesn't seem to like the force redirection via the envoy sidecar. 
However this issue is probably not related to the consul-k8s image, so I think this issue can be closed.

Thanks for the help.
