### ISSUE TITLE
Make log level of consul-sidecar configurable via annotations

### ISSUE THREAD

**Issue by paksu** [hashicorp/consul-k8s#525]
#### Is your feature request related to a problem? Please describe.

Add the ability to configure the log level of `consul-sidecar` containers that get injected to run in the service pods. 

#### Feature Description

At the moment there is no way to control the log level of the side cars which might be useful since they log quite alot of things. I think the best approach here would be to just do this via the annotations, for example `consul.hashicorp.com/sidecar-proxy-log-level` so you can control the log level individual services.

#### Use Case(s)

I think this is a standard feature of pretty much every service.

#### Contributions

Unfortunately I don't have time.

**Comment by david-yu** [comment]
Hi @paksu we actually have the following annotation [hashicorp.com/envoy-extra-args](https://www.consul.io/docs/k8s/connect#consul-hashicorp-com-envoy-extra-args) for adjusting log levels via annotation of Envoy. Is this what you were looking for?

In addition we did a major architecture change in Consul Kubernetes for 0.32.0 of the Helm chart and 0.26.0 of the Consul K8s binary to now handle most of the Connect logic connect webhook injector deployment. We are still planning on providing a solution for JSON logging as shown here: https://github.com/hashicorp/consul-k8s/pull/523

**Comment by david-yu** [comment]
Hi @paksu will close since there seems to be a way to do this today as described above. I have not heard back since replying. Please re-open if you feel that is not the case.
