### ISSUE TITLE
Docker image using non-numeric user, causing problems with 'restricted' PSP

### ISSUE THREAD

**Issue by barrymars** [hashicorp/consul-k8s#560]
#### Question

I am working on deploying Consul into our Kubernetes environment via the helm chart, and finding I am having to hack the helm chart to set the securityContext all over the place, because the consul-k8s docker image runs as 'consul-k8s' rather than a numeric uid...which conflicts with using the standard 'restricted' PSP.

Is there a reason not to use "USER 100" instead of "USER consul-k8s" in the docker image?

**Comment by barrymars** [comment]
in fact this becomes more of an issue, as the injected init containers of services can't be modified as the code (https://github.com/hashicorp/consul-k8s/blob/master/connect-inject/container_init.go) currently has no means of parsing in a securitycontext

So for initial testing I have had to hack the PSPs to allow the consul-connect-inject-init container to run

**Comment by ishustava** [comment]
Hey @barrymars 

Could you help us with some steps on how to reproduce this and understand a bit more what the underlying problem is?

I think the user on Linux already has a numeric UID for user names. When I ssh into a consul-k8s container and run `id` command, I get this:

```
/ $ id
uid=100(consul-k8s) gid=1000(consul-k8s)
```

**Comment by barrymars** [comment]
I'll be able to dig out specifics tomorrow, but it's effectively the same as this - https://stackoverflow.com/questions/49720308/kubernetes-podsecuritypolicy-set-to-runasnonroot-container-has-runasnonroot-and

**Comment by barrymars** [comment]
Yes our situation is almost exactly the same as the stackoverflow question.

We have a [standard](https://kubernetes.io/docs/concepts/security/pod-security-standards/) 'restricted' Pod Security Policy, with the rule:
`runAsUser:
  rule: runAsNonRoot`

Which triggers this [validation call](https://github.com/kubernetes/kubernetes/blob/5648200571889140ad246feb82c8f80a5946f167/pkg/kubelet/kuberuntime/kuberuntime_container.go#L196)
`// Verify RunAsNonRoot. Non-root verification only supports numeric user.
if err := verifyRunAsNonRoot(pod, container, uid, username); err != nil {
    return nil, cleanupAction, err
}`
`case uid == nil && len(username) > 0:
    return fmt.Errorf("container has runAsNonRoot and image has non-numeric user (%s), cannot verify user is non-root", username)`

Which is due to how kubernetes determines the imageUser - https://github.com/kubernetes/kubernetes/blob/2e93b3924ae6eb2b6a2b914fe400a006bd676308/pkg/kubelet/dockershim/helpers.go#L257
`// getUserFromImageUser gets uid or user name of the image user.
// If user is numeric, it will be treated as uid; or else, it is treated as user name.
func getUserFromImageUser(imageUser string) (*int64, string) {
	user := parseUserFromImageUser(imageUser)
	// return both nil if user is not specified in the image.
	if user == "" {
		return nil, ""
	}
	// user could be either uid or user name. Try to interpret as numeric uid.
	uid, err := strconv.ParseInt(user, 10, 64)
	if err != nil {
		// If user is non numeric, assume it's user name.
		return nil, user
	}
	// If user is a numeric uid.
	return &uid, ""
}`

Which in turn is relying on the information returned by 'docker inspect <image_id>'.

Which for the hashicorp/consul-k8s images is `"User": "consul-k8s"`

**Comment by ishustava** [comment]
Thanks for such detailed information @barrymars ! Let me take a look.

**Comment by ishustava** [comment]
Hey @barrymars 

We've updated our docker image to use a numeric user. I've tested with the restricted PSP, and it works.

This change should be included in our next consul-k8s release.

**Comment by barrymars** [comment]
thanks @ishustava 

Look forward to the release
