### ISSUE TITLE
consul-connect-inject-init failing 

### ISSUE THREAD

**Issue by chenjinkai** [hashicorp/consul-k8s#625]
the helm command:
`helm install -f dc1-values.yaml consul ./consul-0.32.1.tgz -n pm5-ms --version "0.32.1" --wait`
the command to install backend application:
`kubectl apply -f static-server.yaml -n pm5-ms`

 I have used the image “hashicorpdev/consul-k8s:2dfffed”, and turn off the `dns.enabled=false`. but i still got the problem as following.
`2021-08-18T02:34:53.420Z [ERROR] Consul login failed; retrying: error="error logging in: Unexpected response code: 403 (rpc error making call: Permission denied)"`
`2021-08-18T02:34:54.446Z [ERROR] Consul login failed; retrying: error="error logging in: Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)"`
`2021-08-18T02:34:55.461Z [ERROR] Consul login failed; retrying: error="error logging in: Unexpected response code: 403 (rpc error making call: rpc error making call: Permission denied)"`
`2021-08-18T02:34:56.474Z [ERROR] Consul login failed; retrying: error="error logging in: Unexpected response code: 403 (rpc error making call: Permission denied)"`
`2021-08-18T02:34:56.474Z [ERROR] Hit maximum retries for consul login: error="error logging in: Unexpected response code: 403 (rpc error making call: Permission denied)"`

[my configurations](https://github.com/chenjinkai/consul-logs)

**Comment by chenjinkai** [comment]
[root@mujup-dev038-10 consul_helm]# kubectl get pods -A
NAMESPACE        NAME                                                          READY   STATUS                  RESTARTS   AGE
default          nfs-client-provisioner-5bf8474d69-fbjs4                       1/1     Running                 7          14d
default          static-client-695c78b555-r57tj                                2/2     Running                 0          30h
default          static-server-5b87cd8cdf-n6dzp                                0/2     Init:CrashLoopBackOff   7          14m
kube-system      calico-kube-controllers-749c5ff7db-mkbbd                      1/1     Running                 2          13d
kube-system      calico-node-5tfgk                                             1/1     Running                 0          13d
kube-system      calico-node-f6m87                                             1/1     Running                 0          13d
kube-system      calico-node-f8zd6                                             1/1     Running                 0          13d
kube-system      coredns-5485fd55c9-b7zrh                                      1/1     Running                 0          14d
metallb-system   controller-676bbcdf6f-4rhk2                                   1/1     Running                 0          22d
metallb-system   speaker-25j8z                                                 1/1     Running                 0          22d
metallb-system   speaker-gvrf9                                                 1/1     Running                 0          22d
metallb-system   speaker-jtcjd                                                 1/1     Running                 0          14d
pm5-ms           consul-connect-injector-webhook-deployment-755cd46d65-6n5bx   1/1     Running                 0          27h
pm5-ms           consul-connect-injector-webhook-deployment-755cd46d65-pxd9q   1/1     Running                 0          27h
pm5-ms           consul-controller-b496f657b-7f8gs                             1/1     Running                 0          27h
pm5-ms           consul-hpf8z                                                  1/1     Running                 0          27h
pm5-ms           consul-mesh-gateway-595f46fb64-m5drj                          2/2     Running                 0          27h
pm5-ms           consul-mesh-gateway-595f46fb64-mg7lw                          2/2     Running                 0          27h
pm5-ms           consul-rnkg9                                                  1/1     Running                 0          27h
pm5-ms           consul-server-0                                               1/1     Running                 0          27h
pm5-ms           consul-server-1                                               1/1     Running                 0          27h
pm5-ms           consul-server-2                                               1/1     Running                 0          27h
pm5-ms           consul-w7slr                                                  1/1     Running                 0          27h
pm5-ms           consul-webhook-cert-manager-7d4d9dbdd5-jf5m8                  1/1     Running                 0          27h

**Comment by chenjinkai** [comment]
![1629356632(1)](https://user-images.githubusercontent.com/2556749/130023273-8d9b6a88-ac42-400b-9532-d07475862d8a.png)

**Comment by david-yu** [comment]
Hi @chenjinkai could you help us understand why you are using that particular image? We don't officially support dev images as those are mainly meant for testing and development for specific PRs. I would recommend switching to a version that is compatible with Helm `0.32.1` like `hashicorp/consul-k8s:0.26.0`.

**Comment by chenjinkai** [comment]
@andriktr Thank you. I'll try it first.

**Comment by chenjinkai** [comment]
@andriktr @david-yu  i have resolved it by add serviceAccountName in my static-server.yaml.

**Comment by andriktr** [comment]
@chenjinkai Yep according consul documentation `If using ACLs, this name must be the same as the Pod's ServiceAccount name.`
Think you can close the issue :)

**Comment by david-yu** [comment]
Thank you @andriktr for following up! Glad to know the issue was solved!
