### ISSUE TITLE
Connect external agents without the need of a DaemonSets

### ISSUE THREAD

**Issue by timmjd** [hashicorp/consul-k8s#634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Feature Description

Provide a strategy how to connect an OnPrem agent to a EKS hosted Consul cluster without the usage of DaemonSets.

#### Use Case(s)

I'm running a hybrid environment with a bunch of OnPrem / EKS / AWS nodes. I'd like to use Consul primary as a service discovery for populating Prometheus scrape config. The EKS where I'd like to deploy Consul is shared across multiple departments, so I'm not allowed to open NodePorts on every node.

Sadly any configuration option I'd looked across the Helm chart and Consul manual (Ingress Gateway / Mesh Gateway) does come with the requirement to enable clients (`client.enabled: true`) and therefore deploy the agents on every node of the EKS cluster wie DaemonSets.

#### Contributions

Is there a way to put the Consul server behind a native Kubernetes LoadBalancer (like a NLB) or an Ingress?

From the blog post [Load Balancing Strategies for Consul](https://www.hashicorp.com/blog/load-balancing-strategies-for-consul) this seems to be proposed but not be part of this Helm chart.

**Comment by ndhanushkodi** [comment]
You could potentially deploy your servers on EKS and have an external client agent on your on-prem node using the strategy described in this doc: https://www.consul.io/docs/k8s/installation/deployment-configurations/clients-outside-kubernetes. Let us know if this would meet your use case.

**Comment by david-yu** [comment]
Closing as there has not been a response in some time. I hope the previous response was helpful!
