### ISSUE TITLE
helm:PreStop hook for client daemonset

### ISSUE THREAD

**Issue by mogggggg** [hashicorp/consul-k8s#637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Is your feature request related to a problem? Please describe.
We're using `consul-helm` just the the `agent` and `consul-sync` components and have noticed that as k8s instances are terminated the agent does not gracefully leave the cluster. This results in us having hundreds of nodes in a `failed` state until they're reaped 72h later.

#### Feature Description
You have `preStop` hooks on a few of components in this repo but not on the client daemonset, is this something that can be added? My understand is that now Kubernetes 1.21 is available the Kubelet can send a SIGTERM to daemonsets which we could use to gracefully exit.

**Comment by david-yu** [comment]
@mogggggg Did we find out more why there were two SIGTERM's being sent? I'm not sure if this issue still stands. Thank you.

**Comment by david-yu** [comment]
Will go ahead and close this issue since we haven't seen a reply since the last response. Hopefully the previous guidance was helpful.
