### ISSUE TITLE
helm:Integrating Vault with Consul

### ISSUE THREAD

**Issue by CodieAusten** [hashicorp/consul-k8s#639]
#### How can one properly configure a vault helm chart such that Vault uses Consul as its backend?  When attempting to install Vault, I am receiving a "connection refused" message, and am unable to initialize Vault.   Thank you in advance. 

I am using using https://github.com/hashicorp/consul-helm/issues/784 as a basis for the solution. 

- Executed the following statement per instructions:
kubectl create secret generic consul-client-ca --from-literal=ca="$(kubectl exec consul-server-0 -- curl -sk https://localhost:8501/v1/connect/ca/roots | jq -r .Roots[0].RootCert)"

I have consul working securely using the following values.yaml. 

global:
  name: consul
  enabled: true
  datacenter: dc1
  gossipEncryption:
    secretName: "consul-gossip-encryption-key"
    secretKey: "key"
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
server:
  replicas: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
connectInject:
  enabled: true
controller:
  enabled: true

Vault values.yaml

server:
  standalone: 
    enabled: false
  extraVolumes:
    - type: secret
      name: consul-client-ca
  affinity: ""
  ha:
    enabled: true
    replicas: 1
    config: |
      ui = true
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "consul" {
        path = "vault"
        address = "127.0.0.1:8501"
        scheme = "https"
        tls_ca_file = "/vault/userconfig/consul-client-ca/ca"
      }  
      service_registration "kubernetes" {}

**Comment by david-yu** [comment]
Closing since this seems to be addressed. Please file a new issue if you need more assistance.

**Comment by CodieAusten** [comment]
Thank you for the information, the recommendations did work nicely.  Thanks again!
