### ISSUE TITLE
helm:Support pod security policies for consul-helm 0.32.0+

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
 * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
 * If you are interested in working on this issue or have submitted a pull request, please leave a **comment**
 
---

### Description

This ticket is to track how many folks need pod security policy support given that PSPs are being deprecated. Currently as of 0.32.0 we do not support PSPs. Please add a 👍 reaction if you need PSP support.

**Comment by david-yu** [comment]
This is now resolved. We in fact do support PSPs however our own acceptance tests were failing so we could not successfully ensure that PSPs could work. The PSP acceptance tests are now running as of https://github.com/hashicorp/consul-k8s/pull/629 and required only changes to our test code.
