### ISSUE TITLE
helm:Consul Snapshot Agent is using client's tolerations

### ISSUE THREAD

**Issue by weichuliu** [hashicorp/consul-k8s#645]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

We deploy the snapshot agent via Helm. And found that the snapshot is running on our k8s control-plane nodes, which is undesired -- snapshot agent should run on normal worker nodes.

The reason that causing the issue is -- snapshot agent is getting tolerations from Consul client ([values.yaml](https://github.com/hashicorp/consul-helm/blob/master/values.yaml#L923), [template yaml](https://github.com/hashicorp/consul-helm/blob/master/templates/client-snapshot-agent-deployment.yaml#L33)). This doesn't make sense. Consul clients are running on every nodes as deamonset, and it is usually set with strong tolerations. In our case, since snapagent also obtained strong tolerance, it landed to control-plane nodes because control-plane has lower hw usage than normal worker nodes.

### Expected behavior

If Consul server is enabled in Helm, snapshot agent should collocate with Consul servers, so that it can get the snapshot from local.

If Consul server is not enabled (that is our case -- our Consul servers are running on baremetal), snapshot agent should run on any normal worker nodes.

Also, the snapshot agent stanza should be moved out from `consul.client` path, simply because snapshot agent doesn't belong to client.

**Comment by david-yu** [comment]
Closing as clients now run as sidecars to Consul servers.
