### ISSUE TITLE
helm:Add support for consul-esm

### ISSUE THREAD

**Issue by prasanjit-enginprogam** [hashicorp/consul-k8s#647]
#### Is your feature request related to a problem? Please describe.

we are using external services registered using /catalog/register endpoint. we need to have [consul-esm](https://github.com/hashicorp/consul-esm) to monitor those external endpoints but we are using helm chart installation in k8s environment. please help bake in consul-esm into the helm chart. 

Here is the [github issue](https://github.com/hashicorp/consul/issues/10057) raised for more context.

**Comment by TJM** [comment]
I was thinking consul-esm would be its own helm chart, rather than be baked into this one, but I could go either way. I will vote for this one too. See Also: https://github.com/hashicorp/consul-esm/issues/121
