### ISSUE TITLE
helm:Use consul login/auth method for consul-k8s component ACL tokens instead of kube secrets

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Description

Switch to using `consul login` inside `consul-k8s` components to get ACL tokens instead of `server-acl-init` minting ACL tokens and then writing them to kube secrets.

**Comment by david-yu** [comment]
Closing as we now utilize the kubernetes auth methods to retrieve ACL tokens instead of minting ACL tokens via Kubernetes Secrets when ACLs are enabled in Consul K8s.
