### ISSUE TITLE
consul-helm: Support using Vault for all secrets

### ISSUE THREAD

**Issue by lkysow** [hashicorp/consul-k8s#656]
Would be great to support be able to retrieve all secret material: ACL tokens, TLS certs, etc. from Vault.

**Comment by ultrafear** [comment]
Any updates on this feature?

**Comment by ishustava** [comment]
We're working on it right now. Stay tuned!

**Comment by david-yu** [comment]
Closing as this is mostly addressed by: https://github.com/hashicorp/consul-k8s/pull/904. We'll work on addressing the multi-dc capabilities in a future release.
