### ISSUE TITLE
helm:Configurability of readiness probes

### ISSUE THREAD

**Issue by cerebrate** [hashicorp/consul-k8s#658]
It would be very useful if it was possible to configure the parameters of the readiness and liveness probes implemented by the chart. At times of high load, I frequently find Consul servers and even occasionally agents being terminated due to failures of readiness probes for their pods, and so far as I can tell, there is no actual underlying problem that would justify this termination - merely a slow response due to load.

**Comment by david-yu** [comment]
@cerebrate or @TJM Are the issues still occurring with the latest Consul 1.12 or 1.13.x releases? If so, do you have a PR that we could review that could perhaps address the sort of issues you are seeing during Consul Server startup?

**Comment by cerebrate** [comment]
I am no longer experiencing the issue, but unfortunately I can't tell you if it would otherwise have gone away with the latest releases since, for me, it went away with a hardware upgrade. Sorry I don't have more useful information.

**Comment by david-yu** [comment]
Closing as no feedback was given based on current releases of Consul K8s and Consul. Please open a new issue if more attention is needed.
