### ISSUE TITLE
helm:make volumeClaimTemplates .metadata.name fully configurable

### ISSUE THREAD

**Issue by deantchi** [hashicorp/consul-k8s#659]
Due to the deprecation the stable/consul chart, I'm trying to migrate from the stable/consul chart over to the hashicorp/consul-helm chart without having to migrate data.  is it possible to make the the volumeClaimTemplates .metadata.name fully configurable so it can just assume the original PVCs which is `datadir`? https://github.com/helm/charts/blob/master/stable/consul/templates/consul-statefulset.yaml#L265

https://github.com/hashicorp/consul-helm/blob/master/templates/server-statefulset.yaml#L277

**Comment by david-yu** [comment]
Will close this, as it seems this was mainly related to the migration from the old chart from helm.sh charts around 2 years ago. If you do feel this is still needed please open up a PR.
