### ISSUE TITLE
helm:Pass additional arguments to MeshGateway Envoy

### ISSUE THREAD

**Issue by tasansga** [hashicorp/consul-k8s#660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

The official documentation for Consul (https://www.consul.io/commands/connect/envoy) suggests to pass optional arguments to envoy like this:

`$ consul connect envoy -sidecar-for web -- -l debug`

Apparently there's no way to pass these additional arguments to Envoy sidecars within MeshGateway through the Helm chart though? How can we pass additional arguments to specifically MeshGateway's Envoy using the Helm chart?

**Comment by david-yu** [comment]
This logLevel requirement could likely be addressed cleanly with a good UX via https://github.com/hashicorp/consul-k8s/issues/1256, however I'm curious if other mesh Gateway flags are needed here.

**Comment by david-yu** [comment]
Will go ahead and close as now logLevel should be available via meshGateways via Helm.
