### ISSUE TITLE
helm:How to use deregister_critical_service_after config parameter?

### ISSUE THREAD

**Issue by dontlaugh** [hashicorp/consul-k8s#665]
I'm experimenting with using the catalog sync to register a suite of services for environments that are short lived: a few hours at most.

I'd like to keep the transient services from hanging around forever in my catalog. My understanding is that `deregister_critical_service_after` is a configuration one can apply to a service.

Will this work? How do I apply this configuration when using the helm chart?

**Comment by david-yu** [comment]
Closing as we don't plan on implementing this in catalog sync. This is supported in the service mesh use case however.
