### ISSUE TITLE
helm: Configure annotations on acl-init jobs

### ISSUE THREAD

**Issue by alexdulin** [hashicorp/consul-k8s#670]
Currently there is no way to configure annotations on the [acl-init job](https://github.com/hashicorp/consul-helm/blob/master/templates/server-acl-init-job.yaml#L34). This is problematic when using AWS [cloud auto join](https://www.consul.io/docs/agent/cloud-auto-join) to discover external servers on a cluster with applications that block access to the EC2 metadata endpoints, like [Kiam](https://github.com/uswitch/kiam). It would be extremely helpful to be able to specify annotations for the acl-init jobs with something along the lines of: 

```yaml
aclInit:
  annotations: |
    iam.amazonaws.com/role: some-iam-role
```

Alternatively, it could also inherit the annotations of the server/client configuration. 

Without this, the acl-init jobs will always fail due to not being able to discover external servers by being blocked by Kiam or similar.

**Comment by david-yu** [comment]
Closing as addressed by https://github.com/hashicorp/consul-k8s/pull/2525
