### ISSUE TITLE
helm: Clients should be given a unique ACL token with a more restrictive policy

### ISSUE THREAD

**Issue by ishustava** [hashicorp/consul-k8s#676]
Currently, we create one ACL token for all clients with the following policy (ignoring namespaces): 

```hcl
node_prefix "" {
  policy = "write"
}
service_prefix "" {
  policy = "read"
}
```
This policy allows write on any node. 

Ideally, we should follow the principle of least privilege and restrict the policy only to the node that will be using it. This implies creating a unique client token for each pod in the client daemonset.

**Comment by david-yu** [comment]
Closing as this will no longer be applicable as we migrate towards an agentless model for Consul K8s, i.e. the client agents on K8s nodes should be going away so any concerns regarding them using a duplicate ACL token should as well.
