### ISSUE TITLE
helm:After destroying  the helm chart the secrets for token /Service Account/PSP  are not getting deleted

### ISSUE THREAD

**Issue by junaid18183** [hashicorp/consul-k8s#678]
If you deploy the helm chart with `bootstrapACLs: true`  the helm chart creates the following secrets
```
NAME                                        TYPE                                  DATA   AGE
consul-consul-bootstrap-acl-token           Opaque                                1      22h
consul-consul-client-acl-token              Opaque                                1      22h
consul-consul-tls-init-token-vzrvg          kubernetes.io/service-account-token   3      85s
```

Those are not getting deleted if we delete the helm chart.

This causes the issue if you redeploy the helm chart again.

**Comment by david-yu** [comment]
We now have a CLI that is currently in Alpha, and this would handle deletion of PVCs, Service Accounts and secrets for you: https://www.consul.io/docs/k8s/k8s-cli#uninstall. Closing the issue as that is better addressed through a CLI interface instead of Helm.
