### ISSUE TITLE
consul-helm: Support external TLS Certificates from Vault

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/consul-k8s#679]
We can use [`vault-helm`](https://github.com/hashicorp/vault-helm) with its Agent Injector to provide the secrets for Consul.

I would be happy to give a stab at this, if the maintainers think this is one of the good ways to support external certificates.

**Comment by david-yu** [comment]
Closing as is addressed by: https://github.com/hashicorp/consul-k8s/pull/904
