### ISSUE TITLE
helm:Use recommended labels in chart

### ISSUE THREAD

**Issue by rmacduff** [hashicorp/consul-k8s#684]
Are there any plans to start using the recommended standard labels in the templates per the best practices doc: https://github.com/helm/helm/blob/master/docs/chart_best_practices/labels.md

```
app.kubernetes.io/name
helm.sh/chart
app.kubernetes.io/managed-by
app.kubernetes.io/instance
app.kubernetes.io/version
app.kubernetes.io/component
app.kubernetes.io/part-of
```

This would make it easier to search for kubernetes resources and in logs.

**Comment by david-yu** [comment]
We are using component and chart, but not the others mentioned in the original post are not there yet. Please open a PR if you find others that you would like to add to our templates. Closing for now.
