### ISSUE TITLE
Unable to register services in mulitple namespaces following #527

### ISSUE THREAD

**Issue by dschaaff** [hashicorp/consul-k8s#690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

This has actually broken the way we use consul connect in our dev environments. We deploy a full stack of our application for each git branch in it's own kubernetes namespace. This means the same service, with the same name, exists in multiple namespaces by design. We then create a prepared query to only return upstreams in the same namespace.

```
# creates a prepared query that filters on the namespace tag
def create_consul_prepared_query(service,namespace):
    headers = {'content-type': 'application/json',
               'X-Consul-Token': consul_token}
    data = """{"name": "%s-%s",
             "Service": {
                 "Service": "%s",
                 "Tags": ["%s"],
                 "Connect": true
             }
            }"""%(service,namespace,service,namespace)

# use prepared query in upstream annotation
"consul.hashicorp.com/connect-service-upstreams": "prepared_query:example-service-$CI_COMMIT_REF_SLUG:1500"
```

On consul-k8s 0.33 these services are skipped 

```
2021-08-26T23:07:25.804Z        INFO    controller.endpoints    Skipping service registration because a service with the same name but a different Kubernetes namespace is already registered with Consul     {"name": "example-service", "k8s-namespace": "cexample", "existing-k8s-namespace": "example-1621"}
```

This has been working great for us for well over a year. The new behavior to ignore services with the same name in different namespaces prevents us from upgrading beyond consul-k8s 0.25.

I'd consider this a bug since it explicitly broke previous behavior. Can I get some feedback on whether changing this behavior would be considered? I'm happy to provide any other info that would be helpful.
### Environment details

- `consul-k8s` version: 0.33
- `consul-helm` version: 0.33

Additionally, please provide details regarding the Kubernetes Infrastructure, as shown below:
- Kubernetes version: v1.20
- EKS
- AWS VPC CNI

**Comment by ndhanushkodi** [comment]
This PR should resolve the issue: https://github.com/hashicorp/consul-k8s/pull/697, it'll be included in the next release.

**Comment by david-yu** [comment]
Hi @dschaaff thanks for filing. We'll close this issue since the fix for this is now merged. I am curious though why you do choose not name the service differently through something like kustomize to patch the service name with unique prefixes.

**Comment by dschaaff** [comment]
We have a large body of documentation and habit tied to the service names. We also use the service account name for vault auth and it's simpler to have everything line up.
