### ISSUE TITLE
Service tags containing a comma 

### ISSUE THREAD

**Issue by AndyL4N** [hashicorp/consul-k8s#719]
Consul uses comma-separated service tags notation.
But using traefik proxy with consul catalog I found some complications to setup multiple middlewares or entrypoints, required comma in value. For example:
```
'consul.hashicorp.com/service-tags':  |- 
      traefik.http.routers.router1.middlewares=middleware-redirect-https,middleware-ipwhitelist
```
Here Consul will split the second middleware to another tag
Of course, in consul terminology, this does not match the architecture. But the flexibility of the traefik-consul-kubernetes stack is very efficient. Maybe there is some workаround?

**Comment by david-yu** [comment]
Hi @AndyL4N Could you tell us more about your use case? Have you enabled Connect or are you using mainly Catalog Sync? I believe likely do expect commas to separate tags, but I wonder if you attempted to escape that whole tag somehow with with a single or double quote?

**Comment by AndyL4N** [comment]
Hi @david-yu. Currently we are only using Service Sync without Connect.  Sure, we tried many options to escape commas and tags with quotes, double quotes, braces and bracets, backslashes and even replacing with HTML code symbols. Same for escaping only tag values and whole tag line. As I see in listing above it has no sense because whole annotation tag string splits only by commas without any other logic. 

For example this annotations:

```  annotations:
    'consul.hashicorp.com/service-sync': 'true'
    'consul.hashicorp.com/service-tags':  |- 
     env=prod,
      solution=SupperApp,
      traefik.enable=true,
      traefik.http.middlewares.app-ipwhitelist.ipwhitelist.sourcerange=192.168.1.0/24, 
      traefik.http.middlewares.app-redirect-https.redirectscheme.scheme=https,
      traefik.http.routers.app-http.middlewares=app-redirect-https,app-ipwhitelist,
```
will be splitted to something like this:
<pre>
consul catalog services -tags | grep app
my-service-in-consul      <b>app-ipwhitelist</b>,env=prod,solution=SupperApp,traefik.enable=true,
                          traefik.http.middlewares.app-ipwhitelist.ipwhitelist.sourcerange=192.168.1.1/24,
                          traefik.http.middlewares.app-redirect-https.redirectscheme.scheme=https,
                          <b>traefik.http.routers.app-http.middlewares=app-redirect-https</b>
</pre>

Trying to escape whole tag with double quotes doing a similar thing:
<pre>
my-service-in-consul   <b>"traefik.http.routers.app-http.middlewares=app-redirect-https</b>, env=prod,   
                          <b>app-ipwhitelist"</b>,solution=SupperApp,traefik.enable=true,
                          traefik.http.middlewares.app-ipwhitelist.ipwhitelist.sourcerange=192.168.1.1/24,
                          traefik.http.middlewares.app-redirect-https.redirectscheme.scheme=https,
                          
</pre>
If it requires,  I can send you more variants, but result will be the same.

And the case is to register service with Traefik-specific parameters for configuration discovery. Usually these parameters can have many tags contain commas-separated values like headers, endpoints, middlewares, rules and even Regexp expressions.

**Comment by lkysow** [comment]
Using `,` as our separator was obviously the wrong decision there unfortunately given that tags supports commas. Maybe now in order to preserve backwards compatibility we could supports `\,` being converted into a comma?

**Comment by ivanmordor** [comment]
Good afternoon. Any news on this issue? We can make a fix and use a special separator for a non-sign ","

**Comment by ivanmordor** [comment]
@lkysow can we release a fix for this problem as a fix???

**Comment by lkysow** [comment]
Will be in our next release!
