### ISSUE TITLE
Do the sidecars in Consul Connect respect kubernetes probe results ?

### ISSUE THREAD

**Issue by prashantchari** [hashicorp/consul-k8s#72]
I'm currently using the consul connect feature between clusterip services in Kubernetes. I'm noticing traffic flowing through the consul connect service mesh (through their sidecars) to an upstream pod even if the kubernetes readiness probe fails for it.

Does Consul plug into the k8s health/readiness probe state of the pods or is there a way to hook that information into Consul and the sidecars ?

**Comment by lkysow** [comment]
Hi Prashant, they don't currently plug into those probes.

**Comment by lkysow** [comment]
I'm going to use #155 to track this so I'll close this ticket.
