### ISSUE TITLE
Sidecar injection via CLI

### ISSUE THREAD

**Issue by cromefire** [hashicorp/consul-k8s#73]
#### Feature Description

As many (all?) managed kubernetes services do not support custom Webhooks it would be nice if you could perform the inject from the CLI like e.g. Istio supports

#### Use Case(s)

- Managed kubernetes instances
- Clusters where you do not have admin access

**Comment by cromefire** [comment]
Just to be sure: Mutating Webhooks still have to be configured via the CLI right?

**Comment by lkysow** [comment]
This is supported now (https://www.consul.io/docs/platform/k8s/connect.html). The mutating webhook gets added by the consul-helm chart.

I'm going to close this for now but if you still have questions please comment and I'll re-open.
