### ISSUE TITLE
How to sync ingress object  with hostname to consul by consul-k8s?

### ISSUE THREAD

**Issue by owenJiao** [hashicorp/consul-k8s#734]
Please search the existing issues for relevant questions, and use the reaction feature (https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to add upvotes to pre-existing questions.

#### Question

Now my project use consul as service discovery tool in k8s cluster, and my project expose service with ingress, then consul-k8s sync ingress to consul, also can access to service with domain name which is configed to host in ingress.  but I wonder how it works, Could you give me some explanation ? thanks .

**Comment by david-yu** [comment]
Hi @owenJiao we currently don't support this use case today with catalogSync. I've responded to your query on https://github.com/hashicorp/consul-k8s/issues/5#issuecomment-923172535 as well. We are open to contributions on catalogSync, thank you for your feedback.
