### ISSUE TITLE
Allow Consul to mount emptyDir as RAM Disk for data

### ISSUE THREAD

**Issue by cabrinha** [hashicorp/consul-k8s#736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

Consul always creates a PVC for it's data volume, which is nice, but instead of using a PVC, I'd like to use node-local storage or be able to mount an emptyDir as a ram disk for performance gains.

#### Feature Description

`volumeClaimTemplates` needs to be optional: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-statefulset.yaml#L358

`extraVolumes` needs to be able to create the `/consul/data` directory via the `mountPath`: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-statefulset.yaml#L272

`extraVolumes` needs to support the `emptyDir` sub directive: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

#### Use Case(s)

Consul is used as a KV store for Cortex. Grafana Labs has some insight in how to make Consul very performant as a KV store for Cortex:

* https://grafana.com/blog/2020/02/11/how-were-abusing-hashicorps-consul-at-grafana-labs/
* https://grafana.com/go/webinar/logging-with-loki-essential-configuration-settings/

They suggest using a ram disk for the data directory in the form of emptyDir: https://kubernetes.io/docs/concepts/storage/volumes/#emptydir

#### Contributions

I may be able to open a PR to implement this, but it seems this project has a very specific way of deploying consul server, so I'd ask for a little guidance.

**Comment by lkysow** [comment]
Hi Scott, thanks for the well-written feature request. Could you propose what the changes to values.yaml would look like to enable this functionality? Since this is a niche use-case ideally existing users aren't affected.

I think a draft PR without tests and just the templating changes would help to understand what this might look like.

**Comment by cabrinha** [comment]
> Hi Scott, thanks for the well-written feature request. Could you propose what the changes to values.yaml would look like to enable this functionality? Since this is a niche use-case ideally existing users aren't affected.
> 
> I think a draft PR without tests and just the templating changes would help to understand what this might look like.

I'm not sure if the other maintainers will find this change useful: https://github.com/hashicorp/consul-k8s/pull/740

Seems like a lot of changes for what might not be a widely used feature. If it's too much trouble or not needed, I'll be fine writing my own chart since I'm fitting a much more narrow use case.
