### ISSUE TITLE
Custom labels for connectInject, acl init, and mesh gateway pods via Helm

### ISSUE THREAD

**Issue by david-yu** [hashicorp/consul-k8s#759]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Feature Description

This tracks a feature request to provide the ability to apply custom K8s labels on component that are deployed by the Consul K8s helm chart (some of which are already available today). The feature request describes the ability to set pod labels globally using a single config i.e. `global.extraLabels` for the Pods that are deployed by the Helm chart. 

Currently the pods with missing labels include: 
- connect inject
- ~~catalog sync~~
- acl init
- mesh gw

#### Use Case(s)

This allows practitioners to clearly organize which components of a Helm chart are deployed via the Consul K8s helm chart for either compliance reasons or for tracking purposes.

**Comment by jeanmorais** [comment]
@david-yu I've opened a PR to solve this issue. I ended up not including the catalog sync as the `Deployment` already has custom labels ([see here](https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/sync-catalog-deployment.yaml#L29)).

**Comment by david-yu** [comment]
Thank you @jeanmorais! I'll ask someone to review later this sprint. You are correct about catalog sync!

**Comment by david-yu** [comment]
Closing as mentioned in the PR, a better approach would be to do provide global labels instead.
