### ISSUE TITLE
Mount Consul ACL Token Volume with other containers in injected pods

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/consul-k8s#761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

I am trying to "share" the Consul ACL token provided for Consul Connect via pod mutation with other containers in the pod (e.g. Consul Template). 

I have created a new binding rule and corresponding role to bind new policies to the service tokens.

```hcl
resource "consul_acl_binding_rule" "service_roles" {

  # TODO: Check if this is a hard-coded name
  auth_method = "consul-k8s-auth-method"
  description = "Bind service identities authenticated via Kubernetes to additional roles"
  selector    = "serviceaccount.name!=default"
  bind_type   = "role"
  bind_name   = "$${serviceaccount.name}"
}
```

#### Feature Description

Add a new annotation to mount the injected `consul-connect-inject-data` volume to other containers.

#### Use Case(s)

- Allow other users of Consul API (e.g. Consul Template) to share the same ACL token without also having to manage the lifecycle of the token.

#### Contributions

I can work on this if the maintainers think it's a good idea.

**Comment by lkysow** [comment]
1. I think that's a cool idea! What would the annotation look like? Would it be a list of the containers to share the token with?
2. If you override the binding rule you'll need to make sure you create a role ahead of time for every service in your cluster.

**Comment by lawliet89** [comment]
I've started a PR for this in https://github.com/hashicorp/consul-k8s/pull/763

**Comment by lkysow** [comment]
> I think this should be OK? I've not noticed any issues with services that do not have the role.

Ahh I think I just misunderstood. So you're only creating roles for certain services. The rest of them don't need the role and so they just don't get any additional permissions?

> if you think a comma separated list of containers is useful

I think starting with a simple true/false that results in the token being mounted into every container is probably the simplest place to start.

**Comment by lawliet89** [comment]
> Ahh I think I just misunderstood. So you're only creating roles for certain services. The rest of them don't need the role and so they just don't get any additional permissions?

Yep, you're right.

> I think starting with a simple true/false that results in the token being mounted into every container is probably the simplest place to start.

The PR I linked accepts a comma-separated list of container names. It's not very hard to change it to a true/false implementation.
