### ISSUE TITLE
Consul Connect - ECONNRESET's when the Kured daemon triggers reboots

### ISSUE THREAD

**Issue by prashantchari** [hashicorp/consul-k8s#77]
I'm currently using consul 1.4.2, with consul-k8s version 0.5.0 in multiple kubernetes clusters. We also have the Kured service deployed to the clusters in order to perform safe reboots when the nodes are patched. We're noticing ECONNRESET issues when services attempt to call a service on a node that's chosen for a reboot. Am I missing something ?

**Comment by lkysow** [comment]
Hi Prashant,
How are you calling these services? Using Consul Connect, Consul DNS, or Kube DNS?

**Comment by lkysow** [comment]
Hi Prashant,
I'm going to close this for now since we haven't heard back but if you can answer my question we can re-open.
