### ISSUE TITLE
Connect Inject True Config adding CNI Pod as part of Mesh resulting in networking failure

### ISSUE THREAD

**Issue by drpdishant** [hashicorp/consul-k8s#847]
What happened?

I had installed consul to implement service mesh with mTLS for my application services on EKS with HELM chart.
Following are the values I had set for installation:

```bash
global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.10.3
  imageEnvoy: envoyproxy/envoy:v1.18.4
  imageK8S: hashicorp/consul-k8s-control-plane:0.34.1
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 1
ui:
  enabled: true
# connectInject:
  # enabled: true
  # default: true
transparentProxy:    
  defaultEnabled: true
controller:
  enabled: true
prometheus:
  enabled: true
grafana:
  enabled: true
syncCatalog:  
  enabled: true
```
Nothing happend and it worked fine until I attempted to change the instance types for eks managed worker nodes.
It spinned up new nodes and joined them to cluster. But they didn't become ready.

First hint of the issue: 

Node came up with Taint with error message:

```bash
message: 'container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady
        message:docker: network plugin is not ready: cni config uninitialized'
```
After investigating further I check aws-node daemonset, it showed the following error

```bash
Error creating: Internal error occurred: failed calling webhook "consul-connect-injector.consul.hashicorp.com": Post "https://consul-connect-injector-svc.hashicorp.svc:443/mutate?timeout=10s": no endpoints available for service "consul-connect-injector-svc"
```
From this it is clear that with connectInject.enabled: true, consul tried to inject Proxy Side car to CNI plugin Pods, and this in turn created issue in networking, ultimately making all the Nodes NotReady.

**Comment by drpdishant** [comment]
> Hi, two things:
> 
>     1. Do you know which namespace the CNI pods are in? You can exclude that namespace (if on Kube 1.21+) using:
>        ```yaml
>        connectInject:
>          namespaceSelector: |
>            matchExpressions:
>              - key: "kubernetes.io/metadata.name"
>                operator: "NotIn"
>                values: ["kube-system","local-path-storage","your-namespace-here"]
>        ```
> 
>     2. `no endpoints available for service \"consul-connect-injector-svc\"` is worrying. Are there no pods up for that service?

No, the reason being I had deleted the ASG for EKS to avoid billing for weekends, for which I am using terraform module. 
When on Monday I spinned up ASG nodes they all became not ready with the same error, none of the pods started, and I believe it kind of created a circular dependency putting it into a deadlock situation, where consul pods were dependent on CNI, and CNI was dependent on Consul.

**Comment by drpdishant** [comment]
@lkysow 

Even though such scenarios are rare where all the nodes for a cluster will be removed and recreated, Default config for the namespace selecter should not have let this happen according to what's mentioned in the default value.yaml here https://github.com/hashicorp/consul-k8s/blob/03d4b932256b68ba9fdccba4c00951bb3de275be/charts/consul/values.yaml#L1658

**Comment by lkysow** [comment]
That setting `k8sDenyNamespaces` still requires that the mutating webhook be called and then the webhook chooses to ignore that namespace. In your scenario the webhook couldn't be called. The `namespaceSelector` setting stops the webhook from being called at all.

**Comment by lkysow** [comment]
From https://www.eksworkshop.com/beginner/160_advanced-networking/secondary_cidr/configure-cni/ it looks like that daemonset is in the `kube-system` namespace?

So I think if you upgrade to the latest consul-k8s 0.36.0 and you're on Kube 1.21+ then this will be fixed.

**Comment by drpdishant** [comment]
@lkysow Yes the daemonset is in kube-system namespace. As described I have configured the namespaceSelector and deploy the cluster and consul again. Thanks for helping out.
