### ISSUE TITLE
Unknown ACL Bootstrapping Failure: No K8s Secret Bootstrap Token found

### ISSUE THREAD

**Issue by ultrafear** [hashicorp/consul-k8s#870]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

### Overview of the Issue

Disclaimer: I apologize if this is not a bug--_very likely_--and I simply don't understand the necessary setup (`values.yaml` or something else) to successfully bootstrap and extract the ACL bootstrap token. I believe it should be somewhat simple, but I've been pulling my hair for too long...

After deploying Consul in a 3-node EKS cluster with Terraform (two modules: one for the infra and another for the helm_release) and allowing Helm to manage ACL bootstrapping--using the configuration `manageSystemACLs`--the K8s secret I expect to be created does not exist. A `kubectl get secrets` shows nothing but the K8s default-token-xxxxx.

When I check the logs of all the K8s container running a Consul agent, they all indicate that bootstrapping is `false` when it's set in the Helm config. When popping a shell in all the server agents, they all have their respective `/consul/data/acl-tokens.json`, but none of the clients have one. Bootstrapping has failed, but I don't understand why.

#### Versions
- Consul: v1.10.3
- Kubernetes version: v1.22.3
- Helm: v3.7.1

#### Helm Config `values.yml`
```
global:
  name: dev-consul-helm
  image: "hashicorp/consul:1.10.3"
  domain: consul.<domain>.io

  gossipEncryption:
    autoGenerate: true

  acls:
    manageSystemACLs: true

server:
  replicas: 3

ui:
  service:
    type: 'LoadBalancer'
    port:
      http: 80
```
#### Terraform Config
```
...

resource "kubernetes_namespace" "consul-namespace" {
  metadata {
    name                    = "consul-ns"
  }
}

resource "helm_release" "consul" {
  name                      = "consul"
  chart                     = "hashicorp/consul"
  namespace                 = kubernetes_namespace.consul-namespace.metadata.0.name
  values                    = ["${file("helm/values.yaml")}"]
  timeout                   = 240
  reset_values              = true
  recreate_pods             = true
  cleanup_on_fail           = true
}

```
#### K8s Config
_Auto-generated by `aws eks` after successfully deploying the EKS cluster_. This shouldn't be an issue. Please indicate otherwise.

### Logs

Running `kubectl logs -n consul-ns dev-consul-helm-server-0` for example: `Bootstrap: false`; all agents indicate the same thing. Here's an example from server-0:

```
==> Starting Consul agent...
           Version: '1.10.3'
           Node ID: 'a55584a8-6d17-366c-0d5e-0255559d527f'
         Node name: 'dev-consul-helm-server-0'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: false)

==> Log data will now stream in as it occurs:

2021-11-19T18:44:48.519Z [WARN]  agent: bootstrap_expect > 0: expecting 3 servers
2021-11-19T18:44:48.528Z [WARN]  agent.auto_config: bootstrap_expect > 0: expecting 3 servers
...
```
A client logs this:
```
==> Starting Consul agent...
           Version: '1.10.3'
           Node ID: '1b534999-2bdb-9999-8067-fe8dc429982b'
         Node name: 'ip-99-9-9-99.us-west-1.compute.internal'
        Datacenter: 'dc1' (Segment: '')
            Server: false (Bootstrap: false)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, gRPC: 8502, DNS: 8600)
      Cluster Addr: 99.99.99.99 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: true, TLS-Outgoing: false, TLS-Incoming: false, Auto-Encrypt-TLS: false
```
I've removed the rest of the log which includes SERF, Raft, and DNS errors. Please let me know if this could help diagnose the problem.

Any and all help is greatly appreciated! Thank you.

**Comment by ultrafear** [comment]
I should have noted that I can [manually reset the ACL system](https://learn.hashicorp.com/tutorials/consul/access-control-troubleshoot#reset-the-acl-system), but I would like to successfully do this through the Helm chart.

**Comment by lkysow** [comment]
Hi, I do see the ACL secrets generated properly. Are you checking in the right namespace?

My reproduction:

```
ls
terraform.tf      terraform.tfstate values.yaml
```

```
cat terraform.tf
provider "helm" {
  kubernetes {
    config_path = "~/.kube/config"
  }
}

resource "helm_release" "consul" {
  name            = "consul"
  repository      = "https://helm.releases.hashicorp.com"
  chart           = "consul"
  values          = [file("values.yaml")]
  timeout         = 240
  reset_values    = true
  recreate_pods   = true
  cleanup_on_fail = true
}%
```

```
cat values.yaml
global:
  name: dev-consul-helm
  image: "hashicorp/consul:1.10.3"
  gossipEncryption:
    autoGenerate: true
  acls:
    manageSystemACLs: true
server:
  replicas: 1%
```

All the secrets:

```
kubectl get secret
NAME                                                         TYPE                                  DATA   AGE
default-token-pmfk6                                          kubernetes.io/service-account-token   3      4h11m
dev-consul-helm-bootstrap-acl-token                          Opaque                                1      70s
dev-consul-helm-client-acl-token                             Opaque                                1      69s
dev-consul-helm-client-token-dghv5                           kubernetes.io/service-account-token   3      87s
dev-consul-helm-gossip-encryption-autogenerate-token-6ffp8   kubernetes.io/service-account-token   3      94s
dev-consul-helm-gossip-encryption-key                        Opaque                                1      88s
dev-consul-helm-server-acl-init-cleanup-token-xfhxv          kubernetes.io/service-account-token   3      87s
dev-consul-helm-server-acl-init-token-rmv7n                  kubernetes.io/service-account-token   3      87s
dev-consul-helm-server-token-4drxw                           kubernetes.io/service-account-token   3      87s
sh.helm.release.v1.consul.v1                                 helm.sh/release.v1                    1      94s
```

ACL bootstrap secret:

```
kubectl get secret dev-consul-helm-bootstrap-acl-token
NAME                                  TYPE     DATA   AGE
dev-consul-helm-bootstrap-acl-token   Opaque   1      84s
```

Get its value:

```
kubectl get secrets/dev-consul-helm-bootstrap-acl-token --template={{.data.token}} | base64 -D
690a158e-7c1e-0182-7922-63a5600acbac%
```

Check ACL enabled on clients:

```
kubectl exec daemonset/dev-consul-helm -- consul info -token 690a158e-7c1e-0182-7922-63a5600acbac | grep acl
Defaulted container "consul" out of: consul, client-acl-init (init)
	acl = enabled
```

Check ACL enabled on servers:

```
kubectl exec statefulset/dev-consul-helm-server -- consul info -token 690a158e-7c1e-0182-7922-63a5600acbac | grep acl
	acl = enabled
```

**Comment by ultrafear** [comment]
Hi, Luke. Thank you for your reply and test.

It seems like the only difference between your setup and mine is in the `helm_release` Terraform definition. Once I use the default namespace or correctly pass the namespace (which was incorrect previously) in the `helm_release`, I can see the K8s secrets. **The problem was my mistake**. I apologize for the bug submission.

For reference if anyone else is interested I incorrectly referenced `kubernetes_namespace.consul-namespace.metadata.0.name` instead of `kubernetes_namespace.consul-namespace.metadata[0].name` in the Helm resource definition.

That said, I did notice something interesting. Once the cluster successfully bootstrapped the ACL, the UI stopped resolving. After checking the pods, there is a `dns-xxxxx` K8s pod which is created and completed, but not running. _This wasn't running before when the K8s namespace was incorrectly referenced_ in the `helm_release`. Any thoughts?

In the meantime, I'll setup the DNS and report back anything useful. Thanks again for the speedy response!

**Comment by lkysow** [comment]
> That said, I did notice something interesting. Once the cluster successfully bootstrapped the ACL, the UI stopped resolving; it was working before the corrected namespace. After checking the pods, there is a dns-xxxxx K8s pod which is created and completed, but not running. This wasn't running before when the K8s namespace was incorrectly referenced in the helm_release. Any thoughts?

Not sure. I don't think we create a `dns-xxx` Pod so maybe this is something from the kube distribution/cloud provider?

What exactly do you mean by "the UI stopped resolving"?

**Comment by ultrafear** [comment]
I'm not entirely sure either. It was created when I deploy the Helm chart as apart of Terraform.

What I mean is that the K8s service hosting the UI—on the a AWS load-balancer—is not resolving. I need to dig more to understand what the problem now is, but it certainly is not a problem w.r.t. K8s secrets.

Thanks again, and I'll close this issue.
