### ISSUE TITLE
About deployment architecture in production environment

### ISSUE THREAD

**Issue by chenjinkai** [hashicorp/consul-k8s#873]
#### Question
Due to the problems of its own openshift platform (it may be that other applications deployed in the test environment affect the communication between client and server). We hope to deploy client nodes only on some k8s nodes through the k8s labeling mechanism. If we implement such a deployment architecture, it is not clear whether there are adverse effects. I hope to get some official suggestions.

Our current situation：

1. also mesh and no mesh application
2. meshgateway，ingress gateway， terminating gateway

**Comment by kschoche** [comment]
Hi @chenjinkai, thanks for filing this question!
I'm not sure if I understand the full reasoning behind why you'd want to split your cluster up in this way, maybe there is some bug we're unaware of that is introducing adverse behaviour, however, let me try to answer your question directly anyways. :)

The Consul `client-daemonset` is intended to be run on every node, it is responsible for maintaining service registration states as well as forwarding RPC calls to the servers, amongst other things. Service mesh applications register against and are configured with the local consul agent, and `**must**` reside on nodes which have consul agents running.

I'm not aware of any specific requirement for a consul installation to span an entire cluster of k8s nodes, but you would have to ensure that all of your application pods which you intend to be on the service mesh are scheduled on nodes which also have the consul agent pods. For example you would have to apply the same label/taint/etc for your mesh applications as you've done with your consul installation.

I hope this answers your question.

**Comment by chenjinkai** [comment]
@kschoche Your answer is very helpful to us.
