### ISSUE TITLE
Add support for chaining root and intermediate CA certificates to server certificate

### ISSUE THREAD

**Issue by andreas-ahman** [hashicorp/consul-k8s#879]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Is your feature request related to a problem? Please describe.

We have a setup where we're using intermediate CAs, one per datacenter. For our VM's this is not an issue since we manually retrieve the certificates and can append the root and intermediate ca certificates to the server cert.

In kubernetes however we're using the root and intermediate ca chain and the intermediate ca key to sign new certificates. But since these certificates lacks the entire trust chain it fails when trying to communicate with other datacenters.

#### Feature Description

We would like the possibility to specify not only the root ca but the intermediate ca certificate and have the deployment automatically create the certificate chain for signin the certificates and to automatically append the root and intermediate ca certificates to the server certificates to achieve trust. 

#### Use Case(s)

The use case is when you're using intermediate CA's for servers in the Service Mesh and want to add a kubernetes cluster without having to sign the certificates using the root CA.

#### Contributions

Unfortunately I would not be able to help.

**Comment by t-eckert** [comment]
Hi @andreas-ahman,

Thank you for suggesting this feature. I can see how it would be useful. We will triage it and keep you in the loop.

**Comment by brucec5** [comment]
This is also a limitation when using Vault as the secrets backend.

**Comment by david-yu** [comment]
Closing as we now have a solution where we present the intermediate as part of the chain when provisioning the server cert with the Vault secrets backend.
