### ISSUE TITLE
Pods not starting after a Helm install

### ISSUE THREAD

**Issue by jarredatcerner** [hashicorp/consul-k8s#893]
#### Overview of the Issue

I'm trying to install consul into a Tanzu Standard K8's cluster. After the install (steps below) I receive a success message but the pods for Consul never start.

#### Reproduction Steps

Steps to reproduce this issue, eg:

1. helm install consul hashicorp/consul --set global.name=consul --create-namespace -n consul
2. kubectl get pods --selector app=consul
3. kubectl get pods   
No resources found in consul namespace.

### Operating system and Environment details

Mac OSX, Tanzu Standard Kubernetes.

### Log Fragments

Without the pods starting I cannot gather logs.

**Comment by lkysow** [comment]
I'd also look at seeing if the daemonst and statefulset get created. I'm guessing there's a permissions issue with scheduling the pods.

Can you show:

```
kubectl get statefulset -n consul
kubectl get daemonset -n consul
kubectl describe statefulset consul-server -n consul
kubectl describe daemonset consul -n consul
```

**Comment by david-yu** [comment]
Hi @jarredatcerner it looks like VMWare Tanzu Community Edition uses multus-cni for its CNI Plugin. My guess is its related perhaps to VMWare Tanzu Community not supporting hotspots on Mac OS X, which is a requirement for us on Consul K8s. We haven't seen any response for a month so I'm closing for now. Please re-open if you get a chance to get the logs requested!
