### ISSUE TITLE
How to upgrade consul for existing provisioned using consul-k8s

### ISSUE THREAD

**Issue by yrsurya** [hashicorp/consul-k8s#895]
#### Question
Is there any option for consul update to modify existing consul deployment that done by using consul-k8s ?

**Comment by t-eckert** [comment]
Hi @yrsurya,

Thank you for your question. In the future, you may have better luck asking general questions like these in the community forum: https://discuss.hashicorp.com/c/consul

From what I understand, you want to update the Consul version in your cluster using Consul on Kubernetes? If so, this page can help: https://www.consul.io/docs/k8s/upgrade 

You can pass in the Consul image you want to deploy to the `values.yaml` file and run `helm upgrade`.

**Comment by t-eckert** [comment]
It was brought to my attention that you may be referring to the `consul-k8s` CLI. In that case, with the next release, there will be an `upgrade` command added that you can use for modifying your deployment.

**Comment by yrsurya** [comment]
Thanks for letting us know about that upgrade feature.. Thomas
