### ISSUE TITLE
Allow specifying ingressClassName for UI ingress

### ISSUE THREAD

**Issue by jmezach** [hashicorp/consul-k8s#897]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

We are currently trying to rollout Consul to our Kubernetes cluster. We have a non-default nginx ingress controller setup that uses a custom ingress class. Unfortunately it appears there is no way to set the ingressClassName for the UI ingress object using the Chart currently, which means we are unable to access the Consul UI on our cluster.

#### Feature Description

By adding the ability to specify an ingressClassName for the UI ingress we can expose the Consul UI from our Kubernetes cluster.

#### Use Case(s)

This is useful if you have a non-default Kubernetes cluster with some additional requirements.

#### Contributions

This would probably not be a big change so I wouldn't mind sending in a PR if it has a chance of being accepted.

**Comment by t-eckert** [comment]
Hi @jmezach,

I think this could be a great feature and we would be open to you submitting it as a PR. Thank you for suggesting it and being willing to develop it.

**Comment by david-yu** [comment]
@jmezach There was a community PR that was submitted not long ago for this feature: https://github.com/hashicorp/consul-k8s/pull/780/files.

Could you tell us if this PR actually works for you as well?
