### ISSUE TITLE
Request for Supported backend storage for Consul Servers

### ISSUE THREAD

**Issue by vanphan24** [hashicorp/consul-k8s#899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

No, this is a request for documentation clarification on backend storage.

#### Feature Description

This is a request to provide clarification on the supported K8s backend storage for Consul servers. Do we have a list of supported storage types, or is it abstracted enough from Consul where we can say we don't care what the storage is. It sounds like there may be some performance considerations so maybe we can recommend using block over some of the other storage types in the [Kubernetes Storage Class ](https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner) list.

#### Use Case(s)

A customer was asking about this since they were using EBS in production and found some odd behaviors. Not a Consul issue, but a K8s+ebs issue, and therefore was looking for alternative storage types to use instead of EBS.

  
#### Contributions

I'm happy to help test and update docs.

**Comment by t-eckert** [comment]
Hi @vanphan24,

Thank you for reaching out with this question. Consul on Kubernetes is not limited to any particular set of storage types however there are considerations when selecting a storage type which are detailed in this documentation: https://www.consul.io/docs/install/performance#read-write-tuning 

Thank you for highlighting this gap in our documentation. We will explicitly call it out in the Values documentation when the user is selecting a storage class that all Kubernetes Storage Classes are available but some are better for certain Consul use cases.

**Comment by vanphan24** [comment]
thanks guys!
