### ISSUE TITLE
sync-catalog: Consul to K8s: ACL tokens

### ISSUE THREAD

**Issue by GregHanson** [hashicorp/consul-k8s#9]
Following the blog https://www.hashicorp.com/blog/consul-and-kubernetes-service-catalog-sync

I have deployed the 0.2.0 consul helm charts in k8s with service sync enabled.  The docs mention that I need ACL tokens configured for services to sync to k8s: https://www.consul.io/docs/platform/k8s/service-sync.html#authentication

I'm a beginner to consul and have not used consul's ACL tokens.  Do I need to create a token or does one already exist? Is the token applied to the sync-catalog pod or to the services as I register them in consul?  The consul-to-k8s docs aren't very clear on this - am I looking in the wrong spot?

**Comment by GregHanson** [comment]
seeing this in the logs of `sync-catalog`:
```
ERROR: logging before flag.Parse: E1003 16:01:09.873694       8 reflector.go:205] pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Endpoints: endpoints is forbidden: User "system:serviceaccount:default:default" cannot list endpoints at the cluster scope
ERROR: logging before flag.Parse: E1003 16:01:09.873777       8 reflector.go:205] pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:default:default" cannot list services in the namespace "default"
ERROR: logging before flag.Parse: E1003 16:01:09.877544       8 reflector.go:205] pkg/mod/k8s.io/client-go@v8.0.0+incompatible/tools/cache/reflector.go:99: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:default:default" cannot list services at the cluster scope
```
RBAC issue?

**Comment by GregHanson** [comment]
I am running on IKS (IBM kubernetes cloud) had to create something along the lines of :
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: consul
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
and then I redeployed my sync-catalog pod to pick up the changes

**Comment by GregHanson** [comment]
I also tried on minikube `version: v0.28.2` and seeing the same error messages in the sync-catalog until creating the rbac rule

**Comment by adilyse** [comment]
Hi @GregHanson,

RBAC support for catalog sync was officially added in v0.4.0, so that should address your RBAC issues. Additionally, I've updated the documentation to make it clearer that an ACL token is only required if ACLs are enabled on the Consul cluster (Consul PR [5302](https://github.com/hashicorp/consul/pull/5302)).

Feel free to reopen if there are any additional issues!
