### ISSUE TITLE
consul injected pods are not starting due to an error in "consul-connect-inject-init" container

### ISSUE THREAD

**Issue by nimrodgans** [hashicorp/consul-k8s#921]
Hey all, I hope I'm following the repo guidelines :)

I'm trying to deploy a simple Consul demo using the following guide:
https://learn.hashicorp.com/tutorials/consul/service-mesh-deploy?in=consul/gs-consul-service-mesh

During that I encountered several issues, such as persistent volume that wasn't created by default, missing permissions and such... those were solved.
My latest issue is with the 'consul-connect-inject-init' container during pods startup (either the demo or my own created pods).
The logs fetched from kubectl logs are:
```
2021-12-09T17:36:36.991Z [ERROR] Unable to get Agent services: error="Get "http://172.16.193.127:8500/v1/agent/services?filter=Meta%5B%22pod-name%22%5D+%3D%3D+%22echo-5cf498cfc5-4wh68%22+and+Meta%5B%22k8s-namespace%22%5D+%3D%3D+%22default%22": dial tcp 172.16.193.127:8500: connect: connection refused"
```
I searched a bit online and found that adding the following to my helm values might help, but unfortunately it didn't:
```
client:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
```

Any ideas?

Quick update:
I managed to get past this as well....
Now the latest issue is this:
```
Check to ensure a Kubernetes service has been created for this application. If your pod is not starting also check the connect-inject deployment logs.
```

Feels like a CTF challenge...

**Comment by david-yu** [comment]
Hi @nimrodgans no worries! I transferred this issue over the our `consul-k8s` repo. Could you tell us more about your K8s environment? Which k8s distro and version are you running? 

Are you also deploying HashiCups as found here? https://github.com/hashicorp/learn-consul-kubernetes/tree/main/service-mesh/deploy/hashicups. That has services per deployment which we should have addressed within the example repo for Learn.

**Comment by nimrodgans** [comment]
Hey @david-yu, it actually works now!
The first issue was actually related to the `node-id` which existed from previous runs, that prevented one of the pods from properly running.
Then the issue was as you described, I was missing the service per deployment (I was creating the pod myself this time with my own deployment and not using the demo).
Now using the demo, which in turn created the services required, everything is up and running!
Can close the issue :)

**Comment by david-yu** [comment]
Great to hear! Thanks for following up!
