### ISSUE TITLE
Add ImagePullSecret to the statefulset and daemonset 

### ISSUE THREAD

**Issue by jerem0808** [hashicorp/consul-k8s#959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

---

#### Is your feature request related to a problem? Please describe.

When you use a private Docker registry which needs an username/password to login you need a imagePullSecret to login. 
In the values.yaml we have the possibility to give a list of imagePullSecret but none are used in the statefulset or daemonset.

#### Feature Description

I would expect that in the values.yaml to be able to use an imagePullSecret to download the actual docker images from a docker registry

#### Use Case(s)

When we use a private registry which require a login to pull/push

#### Contributions

no

**Comment by ishustava** [comment]
Hey @jerem0808 

We already allow you to provide it via `gloabal.imagePullSecrets` (https://github.com/hashicorp/consul-k8s/blob/3b3719627ba79539481cc5e27948391e3c5936e3/charts/consul/values.yaml#L102). Does this not work for you?

**Comment by ishustava** [comment]
I'm going to go ahead and close this issue as this feature already exists, but please let us know if this doesn't work for you here or open a new issue. Thanks!

**Comment by jerem0808** [comment]
Hi @ishustava 
i didn't know that we can provide the imagePullSecret through a ServiceAccount. 
I will do more test then and open a new issue if it doesn't work. 
you can close this one thank you
