### ISSUE TITLE
better alternative of exposeGossipAndRPCPorts

### ISSUE THREAD

**Issue by slavonicsniper** [hashicorp/consul-k8s#969]
#### Question

Currently [exposeGossipAndRPCPorts](https://www.consul.io/docs/k8s/helm#v-server-exposegossipandrpcports) makes it possible that an outside consul agent can join a k8s cluster inside k8s. This approach uses a pod hostPort which is not a best practise according [this](https://kubernetes.io/docs/concepts/configuration/overview/#services). What about adding an option in values.yaml to choose a service type (nodePort in this case) for the [server-service.yaml](https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/templates/server-service.yaml)?

**Comment by lkysow** [comment]
Hi, node ports can't be used because they load balance between all instances. Gossip doesn't support load balancing, you must be able to talk directly to a specific instance.

**Comment by slavonicsniper** [comment]
[NodePort: Exposes the Service on each Node's IP at a static port (the NodePort). A ClusterIP Service, to which the NodePort Service routes, is automatically created. You'll be able to contact the NodePort Service, from outside the cluster, by requesting NodeIP:NodePort.](https://kubernetes.io/docs/concepts/services-networking/service/#:~:text=NodePort%3A%20Exposes%20the%20Service%20on%20each%20Node%27s%20IP%20at%20a%20static%20port%20(the%20NodePort).%20A%20ClusterIP%20Service%2C%20to%20which%20the%20NodePort%20Service%20routes%2C%20is%20automatically%20created.%20You%27ll%20be%20able%20to%20contact%20the%20NodePort%20Service%2C%20from%20outside%20the%20cluster%2C%20by%20requesting%20%3CNodeIP%3E%3A%3CNodePort%3E.)

**Comment by ishustava** [comment]
Hey @slavonicsniper 

Could you add more context to the quote/link you've provided? I don't think it contradicts to what Luke mentioned above.

**Comment by slavonicsniper** [comment]
A service with the type `nodePort` does not load balance the traffic, instead a port from a range is exposed on each node. So we can directly contact each node which is a member of the cluster.

**Comment by slavonicsniper** [comment]
You're right, sorry for that. I guess there's no other way to make this happen then so will close this issue. Thanks for your time though.
