### ISSUE TITLE
Add custom metadata to service when injecting services

### ISSUE THREAD

**Issue by filintod** [hashicorp/consul-k8s#97]
I'm looking at some integrations with Ambassador and Gloo and it would be nice if the Sync service (specially the sink.go file) would allow some kind of plugin or calling an external service to get metadata (annotations, labels, etc). That way when the service is created in K8S it also contains the annotations/labels or even create an ingress for ingress controllers or being able to provide a golang template snippet to be inserted (like Helm).

During configuration we would provide an endpoint to get extra metadata information to add to the service that the Sync service injects into K8S. Or provide a golang template snipppet to be executed that would add that annotation and/or labels to the metadata section of the service.

**Comment by lkysow** [comment]
Hi Filinto,
Can you explain in more detail how that would help with integration with Ambassador and Gloo? What would the template or external call look like?
Thanks!

**Comment by filintod** [comment]
For example an external (ie VM) service being registered into K8S via consul sync agent, could have its annotations augmented with, in the case of Ambassador, some prefix regex:
```
---
apiVersion: ambassador/v1
kind:  Mapping
name:  qotm_mapping
prefix: "/(v1|v2)/qotm/.*"
prefix_regex: true
service: {{ service.name }}
```

**Comment by filintod** [comment]
reopen, accidental close

**Comment by adilyse** [comment]
Hi @filintod,

Would you be willing to give a little more detail about what the templating or external calls would look like in the scenario you've described?

Thanks!

**Comment by lkysow** [comment]
Closing for now since we haven't heard back.
