### ISSUE TITLE
Can't get things running on kind without a change

### ISSUE THREAD

**Issue by mikebell90** [hashicorp/consul-k8s#990]
Basically unless you add "local-path-storage" to excluded namespaces, everything goes pear shaped, since that pod itself must run happily.

Can this be documented somewhere?

Also was surprised to find your mutating webhookconfiguration didn't populate namespaceselector, and therefore I assume (wrongly?) this is done in code? It really shouldn't be - that should all be in the externalized web hook configuration

**Comment by lkysow** [comment]
Hi Mike, we already add this by default: https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml#L1784. What version are you on? This was added in 0.36.0 (https://github.com/hashicorp/consul-k8s/blob/main/CHANGELOG.md#0360-november-02-2021)

**Comment by mikebell90** [comment]
Ah I see.

**Comment by mikebell90** [comment]
Probably should update docs @lkysow https://learn.hashicorp.com/tutorials/consul/service-mesh-deploy?in=consul/gs-consul-service-mesh still pins 0.35.0

**Comment by david-yu** [comment]
Thanks @mikebell90 We've merged changes to reflect the latest Helm chart on the learn guide. The update should be up soon!
